SELECT A.INVOICE_AMOUNT, A.* FROM PS_BI_HDR A
WHERE A.INVOICE = '0000002882' ;

SELECT A.USER_AMT1, A.* FROM PS_BI_LINE A
WHERE A.INVOICE = '0000002882' ;

SELECT A.BAL_AMT, A.* FROM PS_ITEM A
WHERE A.ITEM = '0000002882' ;

select SUM(BAL_AMT) FROM PS_ITEM WHERE BUSINESS_UNIT = 'AR002' AND ITEM BETWEEN '0000002840' and '0000011967';

SELECT A.ITEM, A.DUE_DT, A. AGING_CATEGORY FROM PS_ITEM A
WHERE  A.CUST_ID = '0000000680'
AND A.ITEM_STATUS = 'O' ;

 SELECT B.CLASS_FLD, B.OPERATING_UNIT, B.DEPTID, A.CUST_ID,  D.NAME1 | | ' ' | |  D.NAME2 | | ' ' | |  D.NAME3, A.ITEM, TO_CHAR(A.DUE_DT,'YYYY-MM-DD'), A.CONTRACT_NUM, A.BAL_AMT, TO_DATE(sysdate ,'YYYY-MM-DD') - TO_DATE( TO_CHAR(A.DUE_DT,'YYYY-MM-DD'),'YYYY-MM-DD'), SUM( DECODE( A.AGING_CATEGORY, '01',  B.MONETARY_AMOUNT, 0)), SUM( DECODE( A.AGING_CATEGORY, '02',  B.MONETARY_AMOUNT, 0)), SUM( DECODE( A.AGING_CATEGORY, '03',  B.MONETARY_AMOUNT, 0)), SUM( DECODE( A.AGING_CATEGORY, '04',  B.MONETARY_AMOUNT, 0)), SUM( DECODE( A.AGING_CATEGORY, '05',  B.MONETARY_AMOUNT, 0)), SUM( DECODE( A.AGING_CATEGORY, '06',  B.MONETARY_AMOUNT, 0)), SUM( DECODE( A.AGING_CATEGORY, '07',  B.MONETARY_AMOUNT, 0)), SUM( DECODE( A.AGING_CATEGORY, '08',  B.MONETARY_AMOUNT, 0)), SUM( DECODE( A.AGING_CATEGORY, '09',  B.MONETARY_AMOUNT, 0)) 
  FROM PS_ITEM A, PS_ITEM_DST B, PS_CUSTOMER D 
  WHERE ( A.BUSINESS_UNIT = B.BUSINESS_UNIT 
     AND A.CUST_ID = B.CUST_ID
     AND A.CUST_ID = '0000000680' 
     AND A.ITEM = B.ITEM 
     AND A.ITEM_LINE = B.ITEM_LINE 
     AND B.ACCOUNT NOT IN ('25000') 
     AND A.CUST_ID = D.CUST_ID 
     AND B.ACCOUNT = '11260' 
     AND A.BAL_AMT <> 0 ) 
  GROUP BY  B.CLASS_FLD,  B.OPERATING_UNIT,  B.DEPTID,  A.CUST_ID,   D.NAME1 | | ' ' | |  D.NAME2 | | ' ' | |  D.NAME3,  A.ITEM,  TO_CHAR(A.DUE_DT,'YYYY-MM-DD'),  A.CONTRACT_NUM,  A.BAL_AMT,  TO_DATE(sysdate ,'YYYY-MM-DD') - TO_DATE( TO_CHAR(A.DUE_DT,'YYYY-MM-DD'),'YYYY-MM-DD') 
  ORDER BY 1, 2, 3, 4, 6 