SELECT DISTINCT PROJECTNAME FROM PSPROJECTITEM 
WHERE PROJECTNAME LIKE '%OPT%'; 

SELECT * FROM PSPROJECTITEM 
WHERE PROJECTNAME ='OPTFINAR_CNDMON_003' ; 

select projectname
  , case when objecttype='0' then 'Records'
  when objecttype='1' then 'Indexes'
  when objecttype='2' then 'Fields'
  when objecttype='3' then 'Format definitions'
  when objecttype='4' then 'Translate values'
  when objecttype='5' then 'Pages'
  when objecttype='6' then 'Menus'
  when objecttype='7' then 'Components'
  when objecttype='8' then 'Record PeopleCode'
  when objecttype='9' then 'Menu PeopleCode'
  when objecttype='10' then 'Queries'
  when objecttype='11' then 'Tree structures'
  when objecttype='12' then 'Trees*'
  when objecttype='13' then 'Access groups*'
  when objecttype='14' then 'Colors'
  when objecttype='15' then 'Styles'
  when objecttype='16' then 'Not used'
  when objecttype='17' then 'Business processes'
  when objecttype='18' then 'Activities'
  when objecttype='19' then 'Roles*'
  when objecttype='20' then 'Process definitions'
  when objecttype='21' then 'Process servers'
  when objecttype='22' then 'Process types'
  when objecttype='23' then 'Process jobs'
  when objecttype='24' then 'Process recurrences'
  when objecttype='25' then 'Message catalog entries*'
  when objecttype='26' then 'Dimensions*'
  when objecttype='27' then 'Cube definitions*'
  when objecttype='28' then 'Cube instance definitions*'
  when objecttype='29' then 'Business interlinks'
  when objecttype='30' then 'SQL definitions'
  when objecttype='31' then 'File layout definitions'
  when objecttype='32' then 'Component interfaces'
  when objecttype='33' then 'Application Engine programs'
  when objecttype='34' then 'Application Engine sections'
  when objecttype='35' then 'Message nodes'
  when objecttype='36' then 'Message channels'
  when objecttype='37' then 'Message definitions'
  when objecttype='38' then 'Approval rule sets'
  when objecttype='39' then 'Message PeopleCode'
  when objecttype='40' then 'Subscription PeopleCode'
  when objecttype='41' then 'Not used'
  when objecttype='42' then 'Component interface PeopleCode'
  when objecttype='43' then 'Application engine PeopleCode'
  when objecttype='44' then 'Page PeopleCode'
  when objecttype='45' then 'Page field PeopleCode'
  when objecttype='46' then 'Component PeopleCode'
  when objecttype='47' then 'Component record PeopleCode'
  when objecttype='48' then 'Component record field PeopleCode'
  when objecttype='49' then 'Images'
  when objecttype='50' then 'Style sheets'
  when objecttype='51' then 'HTML'
  when objecttype='52' then 'Not used'
  when objecttype='53' then 'Permission lists'
  when objecttype='54' then 'Portal registry definitions'
  when objecttype='55' then 'Portal registry structures'
  when objecttype='56' then 'URL definitions'
  when objecttype='57' then 'Application Packages'
  when objecttype='58' then 'Application Package PeopleCode'
  when objecttype='59' then 'Portal Registry User homepages'
  when objecttype='60' then 'Problem type definitions'
  when objecttype='61' then 'Archive templates'
  when objecttype='62' then 'XSLT'
  when objecttype='63' then 'Portal Registry User Favorites'
  when objecttype='64' then 'Mobile pages'
  when objecttype='65' then 'Relationships'
  when objecttype='66' then 'Component Interface Property PeopleCode**'
  when objecttype='67' then 'Optimization Models***'
  when objecttype='68' then 'File References***'
  when objecttype='69' then 'File Reference Type Code***'
  when objecttype='70' then 'Archive object definitions***'
  when objecttype='71' then 'Archive Templates (Type 2)***'
  when objecttype='72' then 'Diagnostic Plug-Ins***'
  when objecttype='73' then 'Analytic Models'
  when objecttype='74' then 'Not Used'
  when objecttype='75' then 'Java Portlet User Preferences'
  when objecttype='76' then 'WSRP Remote Producers'
  when objecttype='77' then 'WSRP Remote Portlets'
  when objecttype='78' then 'WSRP Cloned Portlet Handles'
  when objecttype='79' then 'Services'
  when objecttype='80' then 'Service Operations'
  when objecttype='81' then 'Service Operation Handlers'
  when objecttype='82' then 'Service Operation Version'
  when objecttype='83' then 'Service Operation Routings'
  when objecttype='84' then 'IB Queues'
  when objecttype='85' then 'BIP Template Definitions'
  when objecttype='86' then 'BIP Report Definitions'
  when objecttype='87' then 'BIP File Definitions'
  when objecttype='88' then 'BIP Data Source Definitions'
  when objecttype='89' then 'WSDL'
  when objecttype='90' then 'Message Schemas'
  when objecttype='91' then 'Connected Query Definition'
  when objecttype='92' then 'Logical Schemas'
  when objecttype='93' then 'XML Schemas'
  when objecttype='94' then 'Relational Schemas'
  when objecttype='95' then 'Dependency Documents'
  when objecttype='96' then 'Document Schema'
  when objecttype='97' then 'Essbase Cube Dimensions'
  when objecttype='98' then 'Essbase Cube Outlines'
  when objecttype='99' then 'Essbase Cube Connections'
  when objecttype='100' then 'Essbase Cube Templates'
  when objecttype='101' then 'Delimited Schemas'
  when objecttype='102' then 'Positional Schemas'
  when objecttype='103' then 'Application Data Set Definitions'
  when objecttype='104' then 'Test Definitions'
  when objecttype='105' then 'Test Framework Test Cases'
  when objecttype='106' then 'Application Data Set Bindings'
  when objecttype='107' then 'Feed Definitions'
  when objecttype='108' then 'Feed Categories'
  when objecttype='109' then 'Feed Data Type'
  when objecttype='110' then 'JSON Documents'
  when objecttype='111' then 'Related Content Definition'
  when objecttype='112' then 'Related Content Services'
  when objecttype='113' then 'Related Content Configurations'
  when objecttype='114' then 'Related Content Layouts'
  when objecttype='115' then 'Search Attributes'
  when objecttype='116' then 'Search Definitions'
  when objecttype='117' then 'Search Categories'
  when objecttype='118' then 'Search Contexts'
  when objecttype='119' then 'Integration Groups'
 else 'missing type' end object_type
  , objecttype
  , objectvalue1
  , objectvalue2
  , objectvalue3
  , objectvalue4
  from psprojectitem 
  where projectname = 'OPTFINC_PCC_CRP1';

