SELECT CLASS_FLD, ACCOUNT, OPERATING_UNIT, ACCOUNTING_PERIOD, FISCAL_YEAR,MONETARY_AMOUNT FROM PS_ITEM_DST
WHERE ITEM = '0001000052';

SELECT ACCT_ENTRY_TYPE, CLASS_FLD, ACCOUNT, OPERATING_UNIT, ACCOUNTING_PERIOD, FISCAL_YEAR,MONETARY_AMOUNT FROM PS_BI_ACCT_ENTRY
WHERE INVOICE = '0001000052';
0001000252

SELECT * FROM PS_DST_CODE_TBL
WHERE ACCOUNT = '11186' ;

SELECT * FROM PS_BANK_ACCT_CHRT;
SELECT * FROM PS_BANK_CF_OPTIONS;

SELECT * FROM PS_ITEM_DST
WHERE ACCOUNT = '11186';

SELECT COUNT(*) FROM PS_ITEM
WHERE COLLECTOR = 'TEST'

SELECT * FROM PS_JRNL_HEADER
WHERE JOURNAL_ID = 'OAR0000021';

SELECT * FROM PS_ITEM_ACTIVITY
WHERE ENTRY_TYPE = 'PY'
