SELECT * FROM PS_BI_LINE
WHERE PROJECT_ID <>  ' '
AND BUSINESS_UNIT_PC <> ' ';

SELECT * FROM PS_BI_ACCT_ENTRY
WHERE PROJECT_ID <>  ' '
AND BUSINESS_UNIT_PC <> ' ';

SELECT * FROM PS_BI_LINE_DST
WHERE PROJECT_ID <>  ' ' ;

SELECT * FROM PS_BI_ACCT_ENTRY
WHERE BUSINESS_UNIT_PC <> ' '
AND PROJECT_ID <>  ' ';

SELECT * FROM PS_ITEM_DST
WHERE ITEM = '0001001864'
AND PROJECT_ID <>  ' '
AND BUSINESS_UNIT_PC <> ' ';

UPDATE PS_ITEM_DST SET BUSINESS_UNIT_PC = 'PC001', ACTIVITY_ID = '000000000000001'
WHERE ITEM = '0001001864';

SELECT * FROM PS_PENDING_DST
WHERE PROJECT_ID <>  ' '
AND BUSINESS_UNIT_PC <> ' ';

SELECT * FROM PS_ITEM
WHERE ITEM = '0001001864';

SELECT * FROM PS_BI_HDR
WHERE INVOICE = '0001001864';



