SELECT A.OPRID, A.MAX_WRITE_OFF_AMT, A.MAX_REFUND_AMT, A.MAX_WRITE_OFF_PCT FROM PS_OPR_DEF_TBL_AR A
WHERE A.OPRID = 'JHILL2';

SELECT A.* FROM PSROLEUSER_VW A
WHERE A.OPRID like 'JHI%';

SELECT CUST_ID,ACTION_STATUS,CONDITION_ID,CANCEL_REASON_CD,DATE_ADDED,ACTION_DT,COMPLETION_DATE,DUE_DT,
ACTION_CODE,ACTION_PARM,ANCHOR_AMOUNT,last_maint_dttm,last_maint_oprid,ACTION_OWNER,PROPOSED_AUTOMATED,
PROCESSED_FLG,PROCESS_INSTANCE,COND_ROLE 
FROM PS_ACTION_LST 
WHERE CANCEL_REASON_CD = 'RC';