-- Activity status (Working)
SELECT A.KEY1 AS PCBU, A.KEY2 AS PROJECT, A.KEY3 AS ACTIVITY, A.OLDVALUE, A.NEWVALUE, A.AUDIT_OPRID, A.AUDIT_ACTN, A.AUDIT_STAMP  FROM PSAUDIT A
WHERE A.RECNAME = 'PROJ_ACT_STATUS' 
AND A.FIELDNAME = 'ACTIVITY_STATUS' 
AND A.AUDIT_OPRID = 'VAYALLU' ;

-- Project Manager name change
SELECT A.* FROM PS_OPT_PC_MGR_AUD A
WHERE A.AUDIT_OPRID = 'VAYALLU' ; 

-- Project Manager flag change
SELECT A.* FROM PSAUDIT A 
WHERE A.RECNAME LIKE 'PROJ_TEAM_SCHED' 
AND A.FIELDNAME LIKE 'PROJ_MGR_FLAG' 
AND A.AUDIT_OPRID = 'VAYALLU' ;

-- Billing Rules - Rules Definition Page
SELECT A.* FROM PS_OPT_PC_RLDFN_AU A  ;

-- Billing Rules - Rules condition Page
SELECT A.* FROM PS_OPT_PC_RULCND_V A ;

-- Billing Rules -Billing rates page
SELECT A.* FROM PS_OPT_PC_RLDFN_AU A  ;


 SELECT A.AUDIT_OPRID, TO_CHAR(CAST((A.AUDIT_STAMP) AS TIMESTAMP),'YYYY-MM-DD-HH24.MI.SS.FF'), A.AUDIT_ACTN, A.RECNAME, A.FIELDNAME, A.OLDVALUE, A.NEWVALUE, A.KEY1, A.KEY2, A.KEY3, A.KEY4, A.KEY5, A.KEY6, A.KEY7, A.KEY8, A.KEY9, A.KEY10, A.KEY11, A.KEY12, A.KEY13, A.KEY14, A.KEY15 
  FROM PSAUDIT A 
  WHERE ( A.RECNAME = 'PROJ_TEAM_SCHED' 
     AND A.FIELDNAME = 'PROJ_MGR_FLAG' )
