SELECT A.INVOICE, A.LINE_SEQ_NUM, AR.DST_ID, AR.CLASS_FLD, AR.ACCOUNT, AR.OPERATING_UNIT, A.GROSS_EXTENDED_AMT 
FROM PS_BI_LINE A, PS_BI_LINE_DST_AR AR
WHERE A.INVOICE = AR.INVOICE
AND A.LINE_SEQ_NUM = AR.LINE_SEQ_NUM
AND A.GROSS_EXTENDED_AMT <> 0
AND A.INVOICE = '0001000025' ;

SELECT  AR.ITEM, AR.ITEM_SEQ_NUM, AR.CLASS_FLD, AR.ACCOUNT, AR.OPERATING_UNIT, AR.MONETARY_AMOUNT FROM PS_ITEM_DST AR 
WHERE AR.ITEM = '0001000025' ;

SELECT  AR.ITEM, AR.OPERATING_UNIT, A.BAL_AMT, SUM(AR.MONETARY_AMOUNT), A.BAL_AMT/SUM(AR.MONETARY_AMOUNT)   FROM PS_ITEM_DST AR, PS_ITEM A 
WHERE AR.ITEM = '0001000025' 
AND A.ITEM = AR.ITEM
GROUP BY AR.ITEM, AR.OPERATING_UNIT, A.BAL_AMT ;

SELECT  AR.*, AR.ITEM, AR.CLASS_FLD, AR.ACCOUNT, AR.OPERATING_UNIT, AR.MONETARY_AMOUNT FROM PS_PENDING_DST AR 
WHERE AR.ITEM = '0001000025' ;

SELECT * FROM PS_ITEM
WHERE ITEM =  '0001000025' 
AND ITEM_STATUS = 'O' ;

-----Analysis

SELECT A.INVOICE, A.LINE_SEQ_NUM, AR.DST_ID, AR.CLASS_FLD, AR.ACCOUNT, AR.OPERATING_UNIT, A.GROSS_EXTENDED_AMT 
FROM PS_BI_LINE A, PS_BI_LINE_DST_AR AR
WHERE A.INVOICE = AR.INVOICE
AND A.LINE_SEQ_NUM = AR.LINE_SEQ_NUM
AND A.GROSS_EXTENDED_AMT <> 0
AND A.INVOICE = '0001007255' ;

SELECT  AR.ITEM, AR.ITEM_SEQ_NUM, AR.CLASS_FLD, AR.ACCOUNT, AR.OPERATING_UNIT, AR.MONETARY_AMOUNT FROM PS_ITEM_DST AR 
WHERE AR.ITEM = '0001007255' ;

SELECT  AR.ITEM, AR.OPERATING_UNIT, A.BAL_AMT, SUM(AR.MONETARY_AMOUNT), A.BAL_AMT/SUM(AR.MONETARY_AMOUNT)   FROM PS_ITEM_DST AR, PS_ITEM A 
WHERE AR.ITEM = '0001007255' 
AND A.ITEM = AR.ITEM
GROUP BY AR.ITEM, AR.OPERATING_UNIT, A.BAL_AMT ;

SELECT  AR.*, AR.ITEM, AR.CLASS_FLD, AR.ACCOUNT, AR.OPERATING_UNIT, AR.MONETARY_AMOUNT FROM PS_PENDING_DST AR 
WHERE AR.ITEM = '0001007255' 



select * from ps_BI_LINE_DST_AR where invoice='0001007255'

select * from ps_PENDING_DST where item='0001007255'

SELECT ACCT_ENTRY_TYPE, CLASS_FLD, ACCOUNT, OPERATING_UNIT, ACCOUNTING_PERIOD, FISCAL_YEAR,MONETARY_AMOUNT FROM PS_BI_ACCT_ENTRY
WHERE INVOICE = '0001007255';