select Load_status_BI, count(*) from PS_INTFC_BI
group by load_status_bi;

SELECT * FROM PS_INTFC_BI_AD_CMP WHERE INVOICE = '0001003036' ;

SELECT * FROM PS_INTFC_BI;
SELECT * FROM PS_INTFC_BI_EXSD;
SELECT * FROM PS_INTFC_BIA_TAO ; 
SELECT * FROM PS_INTFC_BI_AEDS ;
SELECT * FROM PS_INTFC_BI2 ;
SELECT * FROM PS_INTFC_BI_NOTE ;
SELECT * FROM PS_INTFC_BI_HDR ;
SELECT * FROM PS_INTFC_BI_TAX ;
