---SQL to find out who approved billing invoice
SELECT * FROM PS_OPT_PC_BUT_AUD
where invoice between 'TMP-0000001573' and 'TMP-0000001580' ;

SELECT * FROM PS_OPT_BI_WRK_EML
WHERE INVOICE IN (
'TMP-0000002349 ') ;
'TMP-0000001011',
'TMP-0000001013',
'TMP-0000001041',
'TMP-0000001042',
'TMP-0000001176',
'TMP-0000001177') ;

SELECT * FROM PS_OPT_PC_BUT_AUD
--WHERE INVOICE IN ('TMP-0000001376','TMP-0000000879')
WHERE INVOICE IN (SELECT INVOICE FROM PS_BI_HDR
WHERE PROJECT_ID BETWEEN '010000000008770' AND '010000000009819' ) ;

SELECT * FROM PS_OPT_BILL_OPT_AU;

SELECT * FROM PS_OPT_BI_TMP_WL
WHERE INVOICE IN (SELECT INVOICE FROM PS_BI_HDR
WHERE PROJECT_ID BETWEEN '010000000008770' AND '010000000009819' ) ;

SELECT INVOICE FROM PS_BI_HDR
WHERE PROJECT_ID BETWEEN '010000000008770' AND '010000000009819' 



SELECT * FROM PS_MESSAGE_LOG WHERE PROCESS_INSTANCE = '334069' ;
SELECT * FROM PS_MESSAGE_LOGPARM WHERE PROCESS_INSTANCE = '334069' ;

SELECT * FROM PS_OPT_BI_WRK_EML WHERE EMAILID LIKE '%humedi%' ;
SELECT * FROM PS_OPT_BI_WRK_EML WHERE EXTRACT(YEAR FROM ADD_DTTM) = '2016' AND EXTRACT(month FROM ADD_DTTM) = '03' AND EXTRACT(DAY FROM ADD_DTTM) = '25' ;

--242 invoices, 179 mails sent
SELECT * FROM PS_OPT_BI_WRK_EML
WHERE INVOICE IN ('TMP-0000002340','TMP-0000000879');
WHERE EXTRACT (YEAR FROM ADD_DTTM) = '2016' 
AND EXTRACT (MONTH FROM ADD_DTTM) = '02'
AND EXTRACT (DAY FROM ADD_DTTM) = '16' 
AND INVOICE IN (SELECT INVOICE FROM PS_INTFC_BI_CMP
WHERE INTFC_ID BETWEEN '8743' AND '8746');

SELECT A.PROJECT_ID, A.INVOICE, A.BILL_STATUS, A.* FROM PS_BI_HDR A
WHERE A.INVOICE NOT IN (SELECT INVOICE FROM PS_INTFC_BI_CMP
WHERE INTFC_ID BETWEEN '7992' AND '7995') ;

SELECT COUNT(*) FROM PS_BI_HDR
WHERE BUSINESS_UNIT = 'BI001'
AND BILL_STATUS <> 'INV' 

SELECT 'X' 
  FROM PS_BI_EXTRCT EX 
 WHERE EX.INVOICE IN ('TMP-0000001352','TMP-0000001351','TMP-0000001350') ;

INSERT INTO PS_OPT_BI_WRK_EML
SELECT A.BUSINESS_UNIT, A.INVOICE, C.EMAILID, 'Y', A.ADD_DTTM 
FROM PS_BI_HDR A, PS_PROJECT_MGR B, PSOPRDEFN C
WHERE A.BILL_STATUS = 'TMP'
AND A.PROJECT_ID <> ' ' 
AND A.PC_DISTRIB_STATUS='N' 
AND A.PROJECT_ID = B.PROJECT_ID
AND B.EFFDT = (SELECT MAX(B_ED.EFFDT)
FROM PS_PROJECT_MGR B_ED
WHERE B.PROJECT_ID = B_ED.PROJECT_ID
AND B.BUSINESS_UNIT = B_ED.BUSINESS_UNIT)
AND C.EMPLID = B.PROJECT_MANAGER    
AND NOT EXISTS ( 
 SELECT 'X' 
  FROM PS_OPT_BI_WRK_EML EML 
 WHERE EML.BUSINESS_UNIT = A.BUSINESS_UNIT 
   AND EML.INVOICE = A.INVOICE 
   AND EML.EMAIL_FLG='Y');



SELECT DISTINCT A.INVOICE, A.PROJECT_ID, B.PROJECT_MANAGER, D.EMAILID FROM PS_INTFC_BI_CMP A, PS_PROJECT_MGR B, PS_BI_HDR C, PSOPRDEFN D
WHERE A.INTFC_ID BETWEEN '8743' AND '8746' 
AND A.PROJECT_ID = B.PROJECT_ID
AND A.BUSINESS_UNIT = C.BUSINESS_UNIT
AND A.INVOICE = C.INVOICE
AND C.BILL_STATUS = 'TMP'
AND C.PROJECT_ID <> ' ' 
AND C.PC_DISTRIB_STATUS='N'
AND D.EMPLID = B.PROJECT_MANAGER    
AND NOT EXISTS ( 
 SELECT 'X' 
  FROM PS_OPT_BI_WRK_EML EML 
 WHERE EML.BUSINESS_UNIT = A.BUSINESS_UNIT 
   AND EML.INVOICE = A.INVOICE 
   AND EML.EMAIL_FLG='Y') ;
   
   
SELECT DISTINCT B.PROJECT_MANAGER,D.NAME  FROM PS_INTFC_BI_CMP A, PS_PROJECT_MGR B, PS_BI_HDR C, PS_PERSONAL_DATA D
WHERE A.INTFC_ID BETWEEN '8743' AND '8746' 
AND A.PROJECT_ID = B.PROJECT_ID
AND A.BUSINESS_UNIT = C.BUSINESS_UNIT
AND A.INVOICE = C.INVOICE
AND C.BILL_STATUS = 'TMP'
AND C.PROJECT_ID <> ' ' 
AND C.PC_DISTRIB_STATUS='N'
AND D.EMPLID = B.PROJECT_MANAGER
AND NOT EXISTS ( 
 SELECT 'X' 
  FROM PS_OPT_BI_WRK_EML EML 
 WHERE EML.BUSINESS_UNIT = A.BUSINESS_UNIT 
   AND EML.INVOICE = A.INVOICE 
   AND EML.EMAIL_FLG='Y') ;
   
 SELECT * FROM PSOPRDEFN ;