-- Billing Interface
SELECT INTFC_ID, CONTRACT_NUM,CNTCT_SEQ_NUM,INVOICE_DT,PO_REF,USER6,BUSINESS_UNIT_PC, PROJECT_ID, BILL_BY_ID, CONTRACT_LINE_NUM, BILL_PLAN_ID, ACCOUNTING_DT FROM PS_INTFC_BI
WHERE INTFC_ID = 293 ;

SELECT INTFC_ID, CONTRACT_NUM,CNTCT_SEQ_NUM,INVOICE_DT,PO_REF,USER6,BUSINESS_UNIT_PC, PROJECT_ID, BILL_BY_ID, CONTRACT_LINE_NUM, BILL_PLAN_ID, ACCOUNTING_DT FROM PS_INTFC_BI
WHERE INTFC_ID = 269 ;

SELECT INVOICE, CONTRACT_NUM,CNTCT_SEQ_NUM,INVOICE_DT,PO_REF,USER6,BUSINESS_UNIT_PC, PROJECT_ID FROM PS_BI_HDR
WHERE INVOICE  IN ( 'TMP-0000000079', 'TMP-0000000079') ;

SELECT A.PROCESS_INSTANCE, A.PC_DISTRIB_STATUS, A.* FROM PS_BI_HDR A
WHERE A.INVOICE  IN ( 'TMP-0000000079', 'TMP-0000000079') ;  

SELECT A.* FROM PS_BI_HDR A
WHERE A.BILL_TO_CUST_ID = '0000000252';

SELECT A.ANALYSIS_TYPE, A.PC_DISTRIB_STATUS, A.* FROM PS_PROJ_RESOURCE A
WHERE A.PROJECT_ID  = '000000000000001' 
AND A.ANALYSIS_TYPE = 'BIL' 
AND A.RESOURCE_TYPE = 'FIXED' ;

SELECT * FROM PS_OPT_BI_WRK_EML 
ORDER BY 5 DESC;



SELECT A.INVOICE_AMOUNT, A.* FROM PS_BI_HDR A
WHERE A.PROJECT_ID <> ' '
AND A.PC_DISTRIB_STATUS = 'N' 
AND A.BILL_STATUS NOT IN ('CAN','NEW') ;

SELECT A.PC_DISTRIB_STATUS, A.* FROM PS_INTFC_BI_CMP A
WHERE A.INVOICE IN ( 'TMP-0000000078', 'TMP-0000000079') ; 

SELECT * FROM PS_INTFC_BI_AEDS
WHERE INTFC_ID = 269 ;

SELECT * FROM PS_BI_WRKSHT_SRCH
SELECT * FROM PS_INTFC_BI WHERE INTFC_ID = 269 ;
SELECT * FROM PS_INTFC_BI_EXSD WHERE INTFC_ID = 269 ;
SELECT * FROM PS_INTFC_BIA_TAO WHERE INTFC_ID = 269 ;
SELECT * FROM PS_INTFC_BI_AEDS WHERE INTFC_ID = 269 ;
SELECT * FROM PS_INTFC_BI2 WHERE INTFC_ID = 269 ;
SELECT * FROM PS_INTFC_BI_NOTE WHERE INTFC_ID = 269 ;
SELECT * FROM PS_INTFC_BI_HDR WHERE INTFC_ID = 269 ;
SELECT * FROM PS_INTFC_BI_TAX WHERE INTFC_ID = 269 ;

SELECT DISTINCT BUSINESS_UNIT FROM PS_INTFC_BI ;


--UPDATE PS_INTFC_BI SET BUSINESS_UNIT = 'BI001'
WHERE BUSINESS_UNIT = 'PC001' ;

--UPDATE PS_INTFC_BI_AEDS SET BUSINESS_UNIT = 'BI001'
WHERE BUSINESS_UNIT = 'PC001' ;

Contract - CON000000005055
Product - 000000000000000310
Cust ID - 0000001298
Unit Amount - 145
Resource ID - 20000000000926

SELECT CLASS_FLD, BI_DISTRIB_STATUS, COUNT(*)  FROM PS_PROJ_RESOURCE
WHERE PROJECT_ID = '000000000000013'
GROUP BY CLASS_FLD, BI_DISTRIB_STATUS ;

SELECT A.PROJECT_ID, A.* FROM PS_BI_WKS_HDR_VW A 
WHERE A.BILL_STATUS = 'NEW' 
AND A.PROJECT_ID <> ' ';

SELECT *  FROM PS_PROJ_RESOURCE
WHERE PROJECT_ID  IN ('000000000000016','000000000000017')
--AND TRANS_DT 
AND ANALYSIS_TYPE = 'BIL' ;

SELECT *  FROM PS_PROJ_RESOURCE
WHERE FOREIGN_AMOUNT = '145' ; 

select * from ps_opt_bi_rl_map2 ;



WHERE RESOURCE_ID IN ('20000000000926', '20000000000925') ;

SELECT * FROM PS_OPT_BI_CC_ADDR ;

select * from dba_objects where object_name='PS_OPT_BI_CC_ADDR' ;

-- Billing Interface with PM and Email address
SELECT A.INTFC_ID, A.CONTRACT_NUM,A.CNTCT_SEQ_NUM,A.INVOICE_DT,A.PO_REF,USER6,A.BUSINESS_UNIT_PC, A.PROJECT_ID, A.BILL_BY_ID, A.CONTRACT_LINE_NUM, A.BILL_PLAN_ID, A.ACCOUNTING_DT,
B.PROJECT_ID, B.PROJECT_MANAGER, C.NAME, D.EMAILID  FROM PS_INTFC_BI A, PS_PROJECT_MGR B, PS_PERSONAL_DATA C, PSOPRDEFN D
WHERE A.ERROR_STATUS_BI <> ' '
AND A.PROJECT_ID = B.PROJECT_ID
AND  B.PROJECT_MANAGER = C.EMPLID 
AND D.EMPLID = C.EMPLID ; 


SELECT B.PROJECT_ID, B.PROJECT_MANAGER, C.NAME, D.EMAILID  FROM PS_PROJECT_MGR B, PS_PERSONAL_DATA C, PSOPRDEFN D
WHERE B.PROJECT_MANAGER = C.EMPLID 
AND D.EMPLID = C.EMPLID ; 

-- File layout OPT_BI_WRK_APP for billing worksheet data

SELECT A.ANALYSIS_TYPE, A.BI_DISTRIB_STATUS, A.GL_DISTRIB_STATUS, SUM(A.RESOURCE_AMOUNT) FROM 
PS_PROJ_RESOURCE A
WHERE A.PROJECT_ID = '000000000000002' 
GROUP BY A.ANALYSIS_TYPE, A.BI_DISTRIB_STATUS, A.GL_DISTRIB_STATUS ;

SELECT A.ANALYSIS_TYPE, A.BI_DISTRIB_STATUS, A.GL_DISTRIB_STATUS, A.* FROM 
PS_PROJ_RESOURCE A
WHERE A.PROJECT_ID = '000000000000002' 
AND A.ANALYSIS_TYPE IN ('OLT','DEF')
AND A.PROCESS_INSTANCE IN ('54968','54805','54891') ;

SELECT * FROM PS_PROJ_RESOURCE
WHERE RESOURCE_ID = '20001420'
AND ANALYSIS_TYPE = 'OLT' ;

update PS_PROJ_RESOURCE set ANALYSIS_TYPE = 'MOD'  
WHERE RESOURCE_ID = '20001420'
AND ANALYSIS_TYPE = 'OLT' ;

--UPDATE PS_BI_HDR SET PROCESS_INSTANCE = '111'
WHERE INVOICE = '0001';

SELECT * FROM PS_CA_LMT_FEE_DTL ;

SELECT DISTINCT USER1 FROM PS_BI_HDR ;

SELECT DISTINCT CUST_ID FROM PS_ITEM
WHERE ITEM_STATUS = 'O' ;