--000100503, 0001004572
SELECT A.INVOICE, COUNT(*) FROM PS_BI_LINE A
GROUP BY A.INVOICE 
HAVING COUNT(*) > 5 
ORDER BY A.INVOICE ;

SELECT A.INVOICE, A.LINE_SEQ_NUM,A.GROSS_EXTENDED_AMT, A.PROJECT_ID, A.*  FROM PS_BI_LINE A
WHERE A.INVOICE = '0001010664' ;

SELECT * FROM PS_INTFC_BI_AD_CMP A
WHERE A.INVOICE = 'TMP-0000000150' ;

SELECT * FROM PS_OPT_CA_DTL_AR A
WHERE A.CONTRACT_NUM = 'CON000000001216' ;

SELECT * FROM PS_OPT_PSA_RLS_HDR A ;
SELECT * FROM PS_PSA_RULES_HDR A ;


SELECT * FROM PSPRSMDEFN WHERE PORTAL_URI_SEG2 = 'OPT_PSA_ACCT_AR' ;     
SELECT * FROM PSPRSMDEFN WHERE PORTAL_OBJNAME = 'EPCA_CREATE_AMEND_CONTRACTS2' ;                       
SELECT * FROM PSPRSMDEFN WHERE PORTAL_OBJNAME = 'EPCO_CUSTOMER_CONTRACTS' ;

SELECT A.INVOICE, A.LINE_SEQ_NUM,A.* FROM PS_BI_LINE_DST_UAR A
WHERE A.INVOICE = '0001010664' ;

SELECT A.INVOICE, COUNT(*) FROM PS_BI_LINE_DST_AR A
WHERE A.ACCOUNT = '11253' 
GROUP BY A.INVOICE ; 

SELECT A.BILL_STATUS, A.PC_DISTRIB_STATUS, COUNT(*) FROM PS_BI_HDR A
WHERE A.PROJECT_ID <> ' '
GROUP BY A.BILL_STATUS, A.PC_DISTRIB_STATUS ;


SELECT A.INVOICE, A.* FROM PS_BI_LINE_DST_AR A
WHERE A.INVOICE = '0001010664' ; 

 
SELECT A.INVOICE, A.LINE_SEQ_NUM, A.ACCT_ENTRY_TYPE,A.MONETARY_AMOUNT, A.GL_DISTRIB_STATUS, A.*  FROM PS_BI_ACCT_ENTRY A
WHERE A.ACCT_ENTRY_TYPE = 'AR'
AND A.ACCOUNT = '11253' ;



SELECT A.ITEM, A.*  FROM PS_ITEM_DST A
WHERE A.ITEM = '0001010664' ;

SELECT A. * FROM PS_JRNL_LN A
WHERE A.DOC_SEQ_DATE = '20-FEB-2015'
AND A.JOURNAL_ID LIKE 'OBI%' ; 


SELECT A.INVOICE, COUNT(*) FROM PS_BI_ACCT_ENTRY A
GROUP BY A.INVOICE 
HAVING COUNT(*) > 10 
ORDER BY A.INVOICE ;

SELECT A.* FROM PS_BI_ACCT_ENTRY A
WHERE A.INVOICE = '0001010664' ;
GROUP BY A.INVOICE 
HAVING COUNT(*) > 10 
ORDER BY A.INVOICE ;