SELECT A.CONTRACT_NUM, A.PROJECT_ID, A.USER6, A.* FROM PS_BI_HDR A
WHERE A.PROJECT_ID LIKE '%68' ;

--CON000000001099
SELECT A.CONTRACT_NUM, A.USER6, A.* FROM PS_BI_HDR A
WHERE A.CONTRACT_NUM = 'CON000000005076' ;

SELECT A.INVOICE, COUNT(*) FROM PS_BI_LINE A
WHERE A.CONTRACT_NUM = 'CON000000005076'  
GROUP BY A.INVOICE ;

SELECT A.INVOICE, A.EMPLID, A.USER5, COUNT(*) FROM PS_BI_LINE A
WHERE A.CONTRACT_NUM = 'CON000000005076'  
GROUP BY A.INVOICE, A.EMPLID, A.USER5 ;

SELECT A.INVOICE, A.EMPLID, A.USER5, COUNT(*) FROM PS_BI_LINE A
WHERE A.EMPLID = '000863049'   
GROUP BY A.INVOICE, A.EMPLID, A.USER5 ;

SELECT A.INVOICE, A.CONTRACT_NUM,A.PC_DISTRIB_STATUS, SUM(A.NET_EXTENDED_AMT), COUNT(*) FROM PS_BI_LINE A
WHERE A.CONTRACT_NUM = 'CON000000005076'
GROUP BY A.INVOICE, A.CONTRACT_NUM,A.PC_DISTRIB_STATUS  ;

SELECT A.ANALYSIS_TYPE, A.BI_DISTRIB_STATUS, A.INVOICE, SUM(A.FOREIGN_AMOUNT), COUNT(*) FROM PS_PROJ_RESOURCE A
WHERE A.CONTRACT_NUM = 'CON000000005076'
AND A.TRANS_DT < '29-JAN-15' 
AND A.RESOURCE_SUB_CAT = 'BILL' 
AND A.ANALYSIS_TYPE = 'BIL'
AND A.BI_DISTRIB_STATUS IN ('W','P') 
GROUP BY A.ANALYSIS_TYPE, A.BI_DISTRIB_STATUS, A.INVOICE
ORDER BY A.ANALYSIS_TYPE ;

SELECT * FROM PS_OPT_PC_BUT_AUD;

SELECT * FROM PS_RUN_BI_WKSH_UPD
WHERE OPRID = 'OPT_BATCH' ;

SELECT DISTINCT CLASS_FLD FROM PS_ITEM_DST ;