----Billing_Invoiced in day

SELECT INVOICE_DT  , COUNT(*) FROM PS_BI_HDR
WHERE BUSINESS_UNIT IN ('BI001','BI002','BI003')
--BUSINESS_UNIT
AND BILL_STATUS = 'INV'
AND TRUNC(DT_INVOICED) > '21-APR-2017'
GROUP BY INVOICE_DT

select * from ps_bi_hdr where business_unit not in ('BI001','BI002','BI003') AND bill_type_id <> 'NTX'
and BILL_STATUS not in ('INV','CAN') and invoice_form_id not in 
('INTL_EMAIL','INTL_PRINT');

SELECT * FROM ps_intfc_bi_cmp where INVOICE IN (select * from ps_bi_hdr where business_unit not in ('BI001','BI002','BI003') AND bill_type_id <> 'NTX'and BILL_STATUS not in ('INV','CAN') and invoice_form_id not in 
('INTL_EMAIL','INTL_PRINT'));

SELECT * FROM PS_BI_HDR where BILL_TO_MEDIA='P' and INVOICE_FORM_ID='EMAIL'

SELECT A.INVOICE, A.TOT_SU_TAX, A.*  FROM PS_BI_HDR A WHERE BILL_STATUS = 'INV' AND DT_INVOICED >= '22-APR-17' --AND INVOICE_AMOUNT <> INVOICE_AMT_PRETAX  AND TOT_SU_TAX <> '0';


SELECT A.INVOICE, A.TOT_SU_TAX, A.*  FROM PS_BI_HDR A
WHERE BILL_STATUS = 'INV'
AND DT_INVOICED >= '22-APR-17'
--AND INVOICE_AMOUNT <> INVOICE_AMT_PRETAX 
AND TOT_SU_TAX <> '0';

SELECT DT_INVOICED,INVOICE_DT, COUNT(*) FROM PS_BI_HDR
WHERE BILL_STATUS = 'INV'
AND DT_INVOICED >= '24-APR-17'
GROUP BY DT_INVOICED, INVOICE_DT;


SELECT * FROM PS_BI_HDR
WHERE INVOICE LIKE '%1053985'
AND TO_CHAR(add_dttm,'DD-MON-YYYY') = '20-APR-2017'
and dt_invoiced >= '22-APR-17'

SELECT DT_INVOICED,ACCOUNT_DT,INVOICE_DT, COUNT(*) FROM PS_BI_HDR
WHERE BILL_STATUS = 'INV'
AND BUSINESS_UNIT LIKE 'BI%'
AND DT_INVOICED >= '24-APR-17'
GROUP BY DT_INVOICED, ACCOUNTING_DT, INVOICE_DT;




