SELECT ANALYSIS_TYPE, BI_DISTRIB_STATUS, COUNT(*) FROM PS_PROJ_RESOURCE A
WHERE A.TRANS_DT BETWEEN '27-JUL-2015' AND '28-AUG-15'
--AND A.BI_DISTRIB_STATUS IN ('P','D','W')
AND A.PM_REVIEWED = 'Y'
AND A.RESOURCE_SUB_CAT = 'BILL'
AND A.ANALYSIS_TYPE IN ('TLX','BIL','ACT') 
GROUP BY ANALYSIS_TYPE, BI_DISTRIB_STATUS ;

SELECT A.ACCT_ENTRY_TYPE, A.CLASS_FLD, A.OPERATING_UNIT, A.ACCOUNT, A.FOREIGN_AMOUNT FROM PS_BI_ACCT_ENTRY A
WHERE INVOICE = '0001000582' ;
--WHERE ACCOUNT = '25000';

SELECT DISTINCT A.PROJECT_ID, A.OPT_PC_RULE_ID, A.OPT_PC_RULE_TYPE, A.CONTRACT_NUM AS RULE_CONTRACT,A.CONTRACT_LINE_NUM AS RULE_CONTRACT_LINE, B.CONTRACT_NUM AS CA_CONTRACT, B.CONTRACT_LINE_NUM AS CA_CONTRACT_LINE, B.PROJECT_ID 
FROM PS_OPT_PC_RULE_HDR A, PS_CA_DETAIL_PROJ B, PS_PROJ_RESOURCE C,PS_OPT_PC_RULE_ACT D
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT_PC
AND A.PROJECT_ID = B.PROJECT_ID
AND D.ACTIVITY_ID = B.ACTIVITY_ID
AND A.EFF_STATUS = 'A'
AND A.OPT_PC_RULE_ID = D.OPT_PC_RULE_ID
AND A.PROJECT_ID = D.PROJECT_ID
AND A.CONTRACT_NUM = B.CONTRACT_NUM
AND A.CONTRACT_LINE_NUM <> B.CONTRACT_LINE_NUM 
AND C.TRANS_DT BETWEEN '27-JUL-2015' AND '28-AUG-15'
AND C.PM_REVIEWED = 'Y'
AND C.RESOURCE_SUB_CAT = 'BILL'
AND C.ANALYSIS_TYPE = 'BIL'
AND A.PROJECT_ID = C.PROJECT_ID
AND C.ACTIVITY_ID = D.ACTIVITY_ID
AND C.PROJECT_ID = D.PROJECT_ID 
AND A.CONTRACT_NUM = C.CONTRACT_NUM ; 



SELECT DISTINCT A.PROJECT_ID, A.ACTIVITY_ID, A.CONTRACT_NUM AS PC_CONTRACT, A.CONTRACT_LINE_NUM AS PC_CONT_LINE, B.CONTRACT_NUM AS RULE_CONTRACT,B.CONTRACT_LINE_NUM
AS RULE_CONTRACT_LINE FROM PS_PROJ_RESOURCE A, PS_OPT_PC_RULE_HDR B, PS_OPT_PC_RULE_ACT C
WHERE 
A.TRANS_DT BETWEEN '27-JUL-2015' AND '28-AUG-15'
AND A.PM_REVIEWED = 'Y'
AND A.RESOURCE_SUB_CAT = 'BILL'
AND A.ANALYSIS_TYPE = 'BIL'
AND B.EFF_STATUS = 'A'
AND A.RES_USER4 = B.OPT_PC_RULE_ID 
AND A.PROJECT_ID = B.PROJECT_ID
AND A.CONTRACT_NUM = B.CONTRACT_NUM 
AND A.CONTRACT_LINE_NUM <> B.CONTRACT_LINE_NUM 
AND A.PROJECT_ID = C.PROJECT_ID
AND A.ACTIVITY_ID = C.ACTIVITY_ID
AND B.PROJECT_ID = C.PROJECT_ID 
AND B.OPT_PC_RULE_ID = C.OPT_PC_RULE_ID ; 



SELECT * FROM PS_OPT_PC_RULE_HDR;


SELECT TA1.PROJECT_ID, TA1.ACTIVITY_ID, TA1.RESOURCE_ID, TA1.contract_num  
FROM PS_CA_BI_PC_TA24 TA1 , PS_PROJECT PRJ , PS_PSA_ORGPRJ_DEFN ORGPRJ WHERE 
ORGPRJ.PROJECT_ID = PRJ.PROJECT_ID AND ORGPRJ.BUSINESS_UNIT = 
PRJ.BUSINESS_UNIT AND TA1.PROJECT_ID = PRJ.PROJECT_ID AND 
TA1.BUSINESS_UNIT_PC = PRJ.BUSINESS_UNIT AND TA1.PROCESS_INSTANCE = 225245 
AND ORGPRJ.EFFDT=(SELECT MAX(EFFDT) FROM PS_PSA_ORGPRJ_DEFN ORGPRJ1 WHERE 
ORGPRJ1.BUSINESS_UNIT=ORGPRJ.BUSINESS_UNIT AND 
ORGPRJ1.PROJECT_ID=ORGPRJ.PROJECT_ID AND ORGPRJ1.EFFDT<=TA1.ACCOUNTING_DT) 
AND NOT EXISTS ( SELECT 'X' FROM PS_PSA_ACCTG_TA24 TA2 WHERE 
TA2.PROCESS_INSTANCE = 225245 AND TA2.RESOURCE_ID = TA1.RESOURCE_ID)
group by TA1.PROJECT_ID, TA1.ACTIVITY_ID, TA1.RESOURCE_ID, TA1.contract_num
having count(TA1.RESOURCE_ID) > 1