---SQL to find out who approved billing invoice
SELECT * FROM PS_OPT_PC_BUT_AUD
where invoice between 'TMP-0000001573' and 'TMP-0000001580' ;

SELECT A.INVOICE, A.BILL_TO_CUST_ID, A.PROJECT_ID, B.ANALYSIS_TYPE, SUM(B.GROSS_EXTENDED_AMT), SUM(B.TAX_AMT), COUNT(*) FROM PS_BI_HDR A, PS_BI_LINE B
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT
AND A.INVOICE = B.INVOICE
AND A.BILL_STATUS = 'TMP'
--AND A.PROJECT_ID <> ' '
AND B.SYSTEM_SOURCE = 'PBI' 
GROUP BY A.INVOICE, A.BILL_TO_CUST_ID, A.PROJECT_ID, B.ANALYSIS_TYPE 
ORDER BY A.INVOICE ;

SELECT BI_DISTRIB_STATUS, COUNT(*) FROM PS_PROJ_RESOURCE
WHERE ANALYSIS_TYPE IN ('TLX','ACT')
GROUP BY BI_DISTRIB_STATUS ;
AND BI_DISTRIB_STATUS = 'N' ;

SELECT * FROM PS_BI_HDR
WHERE PROJECT_ID LIKE '%0000014' ;
