SELECT * FROM PS_BI_HDR_EC ;
-- Message:
SELECT RECNAME,FIELDNAME,FIELDNUM FROM PSRECFIELD WHERE RECNAME IN (SELECT DISTINCT RECNAME FROM PSMSGFLDOVR WHERE MSGNAME LIKE 'BILLING_INVOICE%' AND APMSGVER='VERSION_4'
UNION
SELECT DISTINCT PRNTRECNAME FROM PSMSGFLDOVR WHERE MSGNAME LIKE 'BILLING_INVOICE%' AND APMSGVER='VERSION_4'
)
AND FIELDNAME NOT IN (SELECT DISTINCT FIELDNAME FROM PSMSGFLDOVR WHERE MSGNAME LIKE 'BILLING_INVOICE%' AND APMSGVER='VERSION_4')
ORDER BY 1,3;
-- File Layout
SELECT * FROM PSFLDDEFN WHERE FLDDEFNNAME = 'BILLING_INVOICE_NOTICE'; 
SELECT * FROM PSFLDSEGDEFN WHERE  FLDDEFNNAME = 'BILLING_INVOICE_NOTICE' ORDER BY FLDSEGNAME, FLDSEQNO;
SELECT * FROM PSFLDFIELDDEFN WHERE FLDDEFNNAME = 'BILLING_INVOICE_NOTICE' ORDER BY FLDSEGNAME, FLDSEQNO;
