SELECT COUNT(*) FROM PS_INTFC_BI
WHERE INTFC_ID IN ('9435','9436','9437') ;

SELECT DISTINCT INVOICE, CONTRACT_NUM,CNTCT_SEQ_NUM,INVOICE_DT,PO_REF,USER6,BUSINESS_UNIT_PC, PROJECT_ID, BILL_BY_ID, INVOICE_FORM_ID, CONTRACT_LINE_NUM, BILL_PLAN_ID, ACCOUNTING_DT, BILL_CYCLE_ID FROM PS_INTFC_BI
WHERE INTFC_ID IN ('9435','9436','9437') ;



-- Invoice interface error
SELECT INTFC_ID, CONTRACT_NUM,CNTCT_SEQ_NUM,INVOICE_DT,PO_REF,USER6,BUSINESS_UNIT_PC, PROJECT_ID, BILL_BY_ID, CONTRACT_LINE_NUM, BILL_PLAN_ID, ACCOUNTING_DT FROM PS_INTFC_BI
WHERE ERROR_STATUS_BI <> ' ' ;
SELECT DISTINCT ERROR_STATUS_BI FROM PS_INTFC_BI ;

SELECT * FROM PS_INTFC_BI_AEDS 
WHERE INTFC_ID = '22' ;

010000000000142

SELECT DISTINCT INVOICE, CONTRACT_NUM,CNTCT_SEQ_NUM,INVOICE_DT,PO_REF,USER6,BUSINESS_UNIT_PC, PROJECT_ID, BILL_BY_ID, INVOICE_FORM_ID, CONTRACT_LINE_NUM, BILL_PLAN_ID, ACCOUNTING_DT, BILL_CYCLE_ID FROM PS_INTFC_BI_CMP
--WHERE INTFC_ID = '22' ;
WHERE INVOICE IN ('0001030258','0001030259');
--WHERE PROJECT_ID = '010000000000020';

SELECT DISTINCT INVOICE,CONTRACT_NUM,CNTCT_SEQ_NUM,INVOICE_DT,PO_REF,USER6,BUSINESS_UNIT_PC, PROJECT_ID, BILL_BY_ID, INVOICE_FORM_ID,BILL_TO_MEDIA, ACCOUNTING_DT, BILL_CYCLE_ID, BILL_STATUS 
FROM PS_BI_HDR
--WHERE INVOICE IN ('TMP-0000000117','TMP-0000000118');
WHERE INVOICE IN ('TMP-0000000866','TMP-0000000727');

SELECT A.USER6 FROM PS_BI_HDR A
WHERE A.INVOICE = '0001004374' ;

SELECT A.USER6 FROM PS_BI_HDR A
WHERE A.INVOICE = '0001004374' ;


SELECT INVOICE, CONTRACT_NUM,CNTCT_SEQ_NUM,INVOICE_DT,PO_REF,USER6, BILL_BY_ID, CONTRACT_LINE_NUM, INVOICE_DT FROM PS_BI_HDR
--WHERE CONTRACT_NUM = 'CON000000000920' 
--AND BILL_STATUS = 'NEW' ;
WHERE INVOICE IN ('0001006174','0001006175');
WHERE PROJECT_ID = '010000000000020';

SELECT BILL_STATUS, INVOICE_DT, BI_APPROVAL_STATUS, COUNT(*) FROM PS_BI_HDR 
WHERE BILL_STATUS IN ('NEW', 'RDY','TMR','INV')
AND ( ACCOUNTING_DT > '11-JUL-14' OR ACCOUNTING_DT IS NULL )
GROUP BY BILL_STATUS, INVOICE_DT, BI_APPROVAL_STATUS ;

SELECT INVOICE, BILL_STATUS, INVOICE_DT, ACCOUNTING_DT, BI_APPROVAL_STATUS, USER1 FROM PS_BI_HDR 
WHERE BILL_STATUS not IN ('INV')
AND ( ACCOUNTING_DT < '01-JUL-14' OR ACCOUNTING_DT IS NULL )
AND  INVOICE_DT < '01-JUL-14' ;


SELECT BILL_STATUS, INVOICE_DT, ACCOUNTING_DT, BI_APPROVAL_STATUS, COUNT(*) FROM PS_BI_HDR 
WHERE BILL_STATUS IN ('NEW', 'RDY')
GROUP BY BILL_STATUS, INVOICE_DT, ACCOUNTING_DT, BI_APPROVAL_STATUS ;

SELECT A.INVOICE, A.BILL_TO_CUST_ID, A.ADDRESS_SEQ_NUM, A.BILL_STATUS, A.INVOICE_DT, A.BI_APPROVAL_STATUS FROM PS_BI_HDR A 
WHERE A.BILL_STATUS IN ('RDY') 
ORDER BY A.INVOICE ;

SELECT * FROM PS_BI_HDR
WHERE BILL_STATUS IN ('NEW','RDY')
AND BI_APPROVAL_STATUS = 3 ;

SELECT  A.INVOICE, A.RESOURCE_TYPE, A.EMPLID, A.UNIT_AMT, A.CHARGE_FROM_DT, A.USER3, A.RESOURCE_ID, A.*  FROM PS_BI_LINE A
WHERE A.INVOICE = 'TMP-0000000866'
ORDER BY A.CHARGE_FROM_DT ;

SELECT * FROM PS_BI_HDR 
WHERE BILL_STATUS IN ('NEW', 'RDY')
AND INVOICE_DT > '01-DEC-13'
AND BILL_STATUS = 'RDY' 
AND BI_APPROVAL_STATUS <> 3 ;

-- Bill by ID
SELECT CONTRACT_NUM,CNTCT_SEQ_NUM,INVOICE_DT,PO_REF,USER6,USER8, INTFC_ID,BILL_BY_ID, CONTRACT_LINE_NUM, BILL_PLAN_ID, ACCOUNTING_DT 
FROM PS_INTFC_BI
WHERE INTFC_ID = '3648' ; 
CONTRACT_NUM = 'CON000000000425'
AND INVOICE_DT = '17-DEC-13' ;

SELECT A.INVOICE, A.* FROM PS_BI_HDR A
WHERE A.IVC_PRINTED_DT > '26-OCT-14' ; 

SELECT A.INVOICE, A.USER8 FROM PS_BI_HDR A
WHERE A.CONTRACT_NUM = 'CON000000000425';

SELECT * FROM PS_BI_HDR
WHERE  INVOICE_DT > '01-JAN-14'
AND INVOICE_AMOUNT >= 250000 ;

SELECT INVOICE_DT, SUM(INVOICE_AMOUNT) FROM PS_BI_HDR
GROUP BY INVOICE_DT ;

SELECT INVOICE, COUNT(*) FROM PS_BI_LINE
GROUP BY INVOICE
HAVING COUNT(*) > 10 ;

SELECT BILL_STATUS, EXTRACT(MONTH FROM INVOICE_DT), EXTRACT(YEAR FROM INVOICE_DT), COUNT(*) FROM PS_BI_HDR 
WHERE BILL_STATUS IN ('INV')
AND ( ACCOUNTING_DT > '01-JAN-13' OR ACCOUNTING_DT IS NULL )
GROUP BY BILL_STATUS, EXTRACT(MONTH FROM INVOICE_DT), EXTRACT(YEAR FROM INVOICE_DT) 
ORDER BY 3, 2;

--370 Rows To 617 rows
SELECT COUNT(*) FROM PS_BI_LINE
WHERE INVOICE BETWEEN '0001000957' AND '0001001175' ;

-- 253 rows 
SELECT COUNT(*) FROM PS_BI_LINE
WHERE INVOICE > '0001001175' ;

SELECT CONTRACT_NUM,INVOICE, CNTCT_SEQ_NUM,INVOICE_DT,PO_REF,USER6, BILL_BY_ID, CONTRACT_LINE_NUM, BILL_PLAN_ID, ACCOUNTING_DT FROM PS_INTFC_BI_CMP
WHERE CONTRACT_NUM = 'CON000000000124' ;

SELECT * FROM PS_INTFC_BI_CMP
WHERE INVOICE LIKE '%535' ; 


-- Temporary Invoices
SELECT A.INVOICE, A.BILL_TO_CUST_ID, A.CONTRACT_NUM,B.BILL_PLAN_ID  FROM PS_BI_HDR A, PS_BI_LINE b
WHERE A.BILL_STATUS = 'TMR' AND A.BUSINESS_UNIT = B.BUSINESS_UNIT AND A.INVOICE = B.INVOICE; 

-- Proforma attachments
SELECT * FROM PS_PV_ATTACHMENTS
WHERE ATTACH_DESCR = 'Proforma Image' 
AND SCM_ATTACH_ID LIKE '%2014-01-24%';

-- Invoice attachments
SELECT * FROM PS_PV_ATTACHMENTS
WHERE ATTACH_DESCR = 'Invoice Image'
AND SCM_ATTACH_ID LIKE '%2014-01-24%';

SELECT * FROM PS_PV_ATTACHMENTS
WHERE ATTACH_DESCR NOT IN ('Invoice Image', 'Proforma Image') ;

-- Sales tax
SELECT INVOICE, COUNT(*) FROM PS_BI_LINE
WHERE TAX_AMT <> 0
--AND INVOICE > '0001000956' 
GROUP BY INVOICE ;

SELECT SUM(TAX_AMT) FROM PS_BI_LINE
WHERE TAX_AMT <> 0
AND INVOICE > '0001000956' ;

31 Easter Ave, Weaverville, 96093-1229
SELECT A.INVOICE, A.IVC_PRINTED_DT, A.INVOICE_FORM_ID,A.BILL_STATUS, A.* FROM PS_BI_HDR A
WHERE A.IVC_PRINTED_DT > '26-OCT-14' 
--AND A.INVOICE_FORM_ID = 'PRINT' 
ORDER BY 1;

SELECT A.INVOICE, A.IVC_PRINTED_DT, A.INVOICE_FORM_ID,A.BILL_STATUS, A.* FROM PS_BI_HDR A
WHERE A.INVOICE = '0001007095' ;

select * from ps_bi_extrct where bill_to_media='P' and add_dt>='26-oct-2014' and invoice_action in ('I', 'C') ;

SELECT INVOICE, COUNT(*) FROM PS_BI_LINE
WHERE TAX_AMT <> 0
GROUP BY INVOICE 
HAVING COUNT(*) > 10;