SELECT BUSINESS_UNIT, PROJECT_ID, INVOICE 
  FROM PS_BI_HDR 
 WHERE (BILL_STATUS = 'TMP' 
    OR BILL_STATUS = 'TMR') 
   AND PROCESS_INSTANCE = 0 
   AND (PC_DISTRIB_STATUS <> 'I' 
    OR (PC_DISTRIB_STATUS = 'I' 
   AND EXISTS ( 
 SELECT 'X' 
  FROM PS_BI_WRKSHT_STG STG 
 WHERE PS_BI_HDR.BUSINESS_UNIT = STG.BUSINESS_UNIT 
   AND PS_BI_HDR.INVOICE = STG.INVOICE 
   AND STG.WRKSHT_STATUS IN ('0', '8')))) 
   AND project_id  IN ( 
 SELECT A.project_id 
  FROM PS_PROJECT_MGR A 
 WHERE A.effdt < (select MAX(effdt) from PS_PROJECT_MGR B where B.BUSINESS_UNIT=A.BUSINESS_UNIT   and B.project_id=A.project_id) 
 AND A.project_manager IN ( 
 SELECT emplid 
  FROM psoprdefn ))
 --WHERE oprid='DCLOVIS')) ;
 
  SELECT * FROM PS_PROJECT_MGR
 WHERE     project_id = '010000000000095' ;
 
 SELECT A.PROJECT_ID, COUNT(*) FROM PS_PROJECT_MGR
 WHERE     project_id = '010000000000095' ;
 
 SELECT * FROM PSOPRDEFN WHERE EMPLID = '000562273';