SELECT A.PROCESS_INSTANCE, A.INVOICE, A.BILL_TO_CUST_ID, A.ADDRESS_SEQ_NUM, B.EFF_STATUS, A.INVOICE_DT, B.EFFDT, A.INVOICE_DT-B.EFFDT  FROM PS_BI_HDR A, PS_CUST_ADDRESS B
WHERE A.BILL_STATUS NOT IN ('INV','FNL') 
AND A.BILL_TO_CUST_ID = B.CUST_ID
AND A.ADDRESS_SEQ_NUM = B.ADDRESS_SEQ_NUM
AND B.EFFDT = ( SELECT MAX(EFFDT) FROM PS_CUST_ADDRESS C 
WHERE C.SETID = B.SETID 
AND C.CUST_ID = B.CUST_ID 
AND C.ADDRESS_SEQ_NUM = B.ADDRESS_SEQ_NUM 
AND C.EFFDT <= A.INVOICE_DT) 
--AND B.EFF_STATUS = 'A'
--AND A.INVOICE = '0001010683' ;


SELECT * FROM PS_CUST_ADDRESS
WHERE CUST_ID = '0000000242'; 

SELECT * FROM PS_CUSTOMER
WHERE CUST_ID = '0000000242';

SELECT HDR.* FROM PS_BI_HDR HDR
WHERE INVOICE IN ('0001005658','0001005657') ;

SELECT HDR.* FROM PS_BI_HDR HDR, PS_BI_IVC_FORM FORM , PS_BI_IVC_LAYOUT LAYOUT, PS_CUSTOMER CUST, PS_CUST_ADDRESS CUST_ADDR 
WHERE HDR.INVOICE_FORM_ID = FORM.INVOICE_FORM_ID AND 
FORM.INVOICE_LAYOUT_ID = LAYOUT.INVOICE_LAYOUT_ID AND FORM.PRINT_FORM = 'Y'  
AND HDR.INVOICE_DT IS NOT NULL  AND HDR.TEMPLATE_IVC_FLG = 'N' AND 
HDR.CONSOL_HDR = 'N' AND (HDR.BILL_STATUS NOT IN ('CAN', 'INV', 'FNL', 'TMP', 
'TMR') OR (HDR.BILL_STATUS IN ('TMP', 'TMR') AND HDR.PC_DISTRIB_STATUS <> 
'I')) AND NOT (HDR.BILL_TO_MEDIA = 'E' AND '3' = '1')  AND 
HDR.CONSOL_BUS_UNIT = ' ' AND HDR.CONSOL_INVOICE = ' '  AND CUST.CUST_ID = 
HDR.BILL_TO_CUST_ID AND CUST.SETID = ( SELECT SETID FROM PS_SET_CNTRL_REC C 
WHERE C.SETCNTRLVALUE = HDR.BUSINESS_UNIT AND C.RECNAME = 'CUSTOMER') AND 
CUST_ADDR.SETID = ( SELECT SETID FROM PS_SET_CNTRL_REC S WHERE 
S.SETCNTRLVALUE = HDR.BUSINESS_UNIT AND S.RECNAME = 'CUST_ADDRESS') AND 
CUST_ADDR.CUST_ID = HDR.BILL_TO_CUST_ID AND CUST_ADDR.ADDRESS_SEQ_NUM = 
HDR.ADDRESS_SEQ_NUM AND CUST_ADDR.EFFDT = ( SELECT MAX(EFFDT) FROM 
PS_CUST_ADDRESS A WHERE A.SETID = CUST_ADDR.SETID AND A.CUST_ID = 
CUST_ADDR.CUST_ID AND A.ADDRESS_SEQ_NUM = CUST_ADDR.ADDRESS_SEQ_NUM 
AND A.EFFDT <= HDR.INVOICE_DT) 
AND CUST_ADDR.EFF_STATUS = 'A';