SELECT * FROM PS_CUSTOMER;
SELECT COUNT(*) FROM PS_OPT_COLLEC_RULE;
SELECT * FROM PS_CUST_CGRP_LNK;
SELECT * FROM PS_CUST_DATA;

SELECT DISTINCT A.SETID 
 ,A.CUST_ID
 ,C.SETID
 ,C.CUST_ID
 ,B.COLLECTOR  
  FROM PS_CUSTOMER A 
  ,PS_OPT_COLLEC_RULE B 
  ,PS_CUST_CGRP_LNK C 
  ,PS_CUST_DATA D 
  ,PS_CUST_OPTION F 
 WHERE A.SETID=C.SETID 
   AND A.CUST_ID=C.CUST_ID 
   --AND A.CUST_FIELD_C1_A='N' 
   AND A.CUST_STATUS<>'I' 
   AND C.CUST_GRP_TYPE='COLL' 
   AND A.SETID=B.SETID 
   AND B.SETID=C.SETID 
   AND B.CUSTOMER_GROUP=C.CUSTOMER_GROUP 
   AND ((B.CUST_FIELD_C1_A <> '%' 
   AND SUBSTR(UPPER(A.NAME1),1,1) BETWEEN B.CUST_FIELD_C1_A AND B.CUST_FIELD_C1_B ) 
    OR (B.CUST_FIELD_C1_A = '%' 
   AND SUBSTR(UPPER(A.NAME1),1,1) NOT BETWEEN 'A' AND 'Z' )) 
   AND B.EFF_STATUS='A' 
   AND A.CUST_ID=D.CUST_ID 
   AND D.BAL_AMT BETWEEN B.FROM_AMOUNT AND B.TO_AMOUNT 
   AND F.SETID=A.SETID 
   AND F.CUST_ID=A.CUST_ID 
   AND F.SETID=B.SETID 
   AND F.COLLECTOR<>B.COLLECTOR 
   AND A.SETID = ( 
 SELECT SETID 
  FROM PS_BUS_UNIT_TBL_AR AR 
  , PS_SET_CNTRL_TBL AB 
 WHERE AR.BUSINESS_UNIT = AB.SETCNTRLVALUE 
   AND AR.BUSINESS_UNIT = D.BUSINESS_UNIT) 
   AND B.PRIORITY = ( 
 SELECT MIN(G.PRIORITY) 
  FROM PS_CUSTOMER A1 
  , PS_OPT_COLLEC_RULE G 
  ,PS_CUST_CGRP_LNK C1 
  ,PS_CUST_DATA D1 
  ,PS_CUST_OPTION F1 
 WHERE A1.SETID=C1.SETID 
   AND A1.CUST_ID=C1.CUST_ID 
   AND A1.CUST_FIELD_C1_A='N' 
   AND A1.CUST_STATUS<>'I' 
   AND C1.CUST_GRP_TYPE='COLL' 
   AND A1.SETID=G.SETID 
   AND G.SETID=C1.SETID 
   AND G.CUSTOMER_GROUP=C1.CUSTOMER_GROUP /* AND SUBSTR(UPPER(A.NAME1),1,1) BETWEEN G.CUST_FIELD_C1_A AND G.CUST_FIELD_C1_B */ 
   AND ((G.CUST_FIELD_C1_A <> '%' 
   AND SUBSTR(UPPER(A.NAME1),1,1) BETWEEN G.CUST_FIELD_C1_A AND G.CUST_FIELD_C1_B ) 
    OR (G.CUST_FIELD_C1_A = '%' 
   AND SUBSTR(UPPER(A.NAME1),1,1) NOT BETWEEN 'A' AND 'Z' )) 
   AND G.EFF_STATUS='A' 
   AND A1.CUST_ID=D1.CUST_ID 
   AND D1.BAL_AMT BETWEEN G.FROM_AMOUNT AND G.TO_AMOUNT 
   AND G.PRIORITY>0 
   AND F1.SETID=A1.SETID 
   AND F1.CUST_ID=A1.CUST_ID 
   AND F1.SETID=G.SETID 
   AND F1.COLLECTOR<>G.COLLECTOR 
   AND A1.SETID = ( 
 SELECT SETID 
  FROM PS_BUS_UNIT_TBL_AR AR1 
  , PS_SET_CNTRL_TBL AB1 
 WHERE AR1.BUSINESS_UNIT = AB1.SETCNTRLVALUE 
   AND AR1.BUSINESS_UNIT = D1.BUSINESS_UNIT) )