SELECT * FROM PS_BI_HDR
WHERE BILL_TO_CUST_ID = '0000000540';

SELECT * FROM PS_INTFC_BI_CMP
WHERE BILL_TO_CUST_ID = '0000000538';

SELECT * FROM PS_ACTION_LST 
WHERE CUST_ID = '0000000533' ;

SELECT COUNT(*) FROM PS_CUSTOMER ;

--DELETE FROM PS_ACTION_LST 
WHERE CUST_ID = '0000000540' ;

SELECT DISTINCT CUST_ID FROM PS_ACTION_LST 
WHERE TMPLT_ID = 'STRATEGIC' 
AND ACTION_STATUS = 'NEW' ;

SELECT A.DUE_DT+5, A.* FROM PS_ITEM A
WHERE A.CUST_ID = '0000000628' 
AND A.ITEM_STATUS = 'O' ;

SELECT DISTINCT CUST_ID FROM PS_ITEM WHERE ITEM_STATUS = 'O' ;

SELECT * FROM PS_CUSTOMER WHERE CUST_ID = '0000000540'

SELECT C.CONTACT_ID, CD.COMM_METHOD,CD.* FROM PS_CONTACT_CUST C, PS_CONTACT_CST_DOC CD
WHERE C.SETID = CD. SETID
AND C.CONTACT_ID = CD.CONTACT_ID 
AND C.EFFDT = CD.EFFDT
AND C.CUSTOMER_SETID = CD.CUSTOMER_SETID
AND C.CUST_ID = CD.CUST_ID 
AND CD.EFFDT = ( SELECT MAX(CD1.EFFDT) FROM PS_CONTACT_CST_DOC CD1 WHERE CD1.SETID = CD.SETID AND CD1.CONTACT_ID = CD.CONTACT_ID AND CD1.EFFDT <= sysdate) 
AND CD.DOCUMENT_CD ='INVC' 
AND C.CUST_ID = '0000000540' ;
--AND C.CNTCT_SEQ_NUM = 

-- Corporate customers with having issues
SELECT DISTINCT B.CUST_ID,C.CUSTOMER_GROUP FROM PS_CUSTOMER A, PS_ITEM B, PS_CUST_CGRP_LNK C
WHERE A.CUST_ID <> A.CORPORATE_CUST_ID
AND A.CUST_STATUS = 'A' 
--AND A.CUST_ID IN ('0000000162','0000000540')
AND A.CUST_ID = B.CUST_ID
AND B.ITEM_STATUS = 'O' 
AND B.DUE_DT <= SYSDATE 
AND A.CUST_ID = C.CUST_ID ; 

-- Corporate customers with balance details
SELECT A.CUST_ID,A.NAME1, C.CUSTOMER_GROUP, SUM(B.BAL_AMT) FROM PS_CUSTOMER A, PS_ITEM B, PS_CUST_CGRP_LNK C
WHERE A.CUST_ID <> A.CORPORATE_CUST_ID
AND A.CUST_STATUS = 'A' 
--AND A.CUST_ID IN ('0000000162','0000000540')
AND A.CUST_ID = B.CUST_ID
AND B.ITEM_STATUS = 'O' 
AND B.DUE_DT <= SYSDATE 
AND A.CUST_ID = C.CUST_ID 
GROUP BY A.CUST_ID,A.NAME1, C.CUSTOMER_GROUP;

--List of corporate customers
SELECT DISTINCT A.CUST_ID,C.CUSTOMER_GROUP FROM PS_CUSTOMER A, PS_CUST_CGRP_LNK C
WHERE A.CUST_ID = A.CORPORATE_CUST_ID
AND A.CUST_ID = C.CUST_ID
AND A.CUST_STATUS = 'A'; 


 

SELECT A.DUE_DT+5, A.* FROM PS_ITEM A
WHERE A.CUST_ID = '0000000569' 
AND A.ITEM_STATUS = 'O' ;

 


SELECT * FROM PS_CUSTOMER
WHERE CUST_ID IN ('0000000162','0000000540');

SELECT * FROM PS_CUST_CONTACT
WHERE CUST_ID IN ('0000000162','0000000540');

SELECT * FROM PS_CONTACT_CUST
WHERE CUST_ID IN ('0000000162','0000000540');

