SELECT * FROM PS_AR_ACTION_PRCS ;
-- Actions displayed in the owner action list page
SELECT * FROM PS_ACTION_LST 
WHERE CUST_ID = '0000000362' AND ACTION_STATUS NOT IN ('CMP', 'CAN', 'FUT');

SELECT * FROM PS_ITEM WHERE ITEM = '0001001347'

SELECT * FROM PS_ACTION_LST WHERE CUST_ID = '0000000180' AND TMPLT_ID = 'ALERT';

SELECT * FROM PS_ACTION_LST 
WHERE ACTION_STATUS = 'CMP' AND COMPLETION_DATE = '12-SEP-13'

-- The Condition Monitor process automatically calls the processes to generate the correspondence for all actions whose process flag is Y.
SELECT * FROM PS_CM_CRSPD_IFC ;

SELECT * FROM PS_ACTLST_REASN_VW 
WHERE DUE_DT = '12-SEP-13' AND
TMPLT_ID = 'CORE'

SELECT * FROM PS_AR_DUNNING_CUST WHERE DELIVERY_METHOD = 'E';
SELECT * FROM PS_DUN_CUST WHERE DUN_DT = '12-SEP-13' ;
SELECT * FROM PS_DUN_CUST_DTL WHERE DUN_DT = '12-SEP-13' ;