SELECT * FROM PS_JRNLGEN_DEFN
WHERE ACCTG_DEF_NAME='BI';
-- 1 RECORD
UPDATE PS_JRNLGEN_DEFN SET ACCTG_DEF_NAME='BIDEFN'
WHERE ACCTG_DEF_NAME='BI';
   
SELECT * FROM PS_JRNLGEN_DEFNV
WHERE ACCTG_DEF_NAME='BI';

-- 11 RECORDS
UPDATE PS_JRNLGEN_DEFNV SET ACCTG_DEF_NAME='BIDEFN'
WHERE ACCTG_DEF_NAME='BI';

SELECT * FROM PS_JRNL_HEADER
WHERE ACCTG_DEF_NAME='BI';

UPDATE PS_JRNL_HEADER SET ACCTG_DEF_NAME='BIDEFN'
WHERE ACCTG_DEF_NAME='BI';

