SELECT A.ANALYSIS_TYPE, A.BI_DISTRIB_STATUS, SUM(A.FOREIGN_AMOUNT), COUNT(*) FROM PS_PROJ_RESOURCE A
WHERE A.PROJECT_ID = '000000000000002'
GROUP BY A.ANALYSIS_TYPE, A.BI_DISTRIB_STATUS ;

SELECT A.ANALYSIS_TYPE, A.* FROM PS_PROJ_RESOURCE A
WHERE A.PROJECT_ID = '000000000000002'
--AND RESOURCE_ID IN ('10000214','20001422' )
--AND A.CHARTFIELD1 = 'USAIL034'
AND A.EMPLID LIKE  '%61612'
AND A.BI_DISTRIB_STATUS <> 'D';



 SELECT B.DESCR, B.PROJECT_TYPE, C.DESCR254, B.PROJECT_USER1, B.PROJECT_USER2, TO_CHAR(B.START_DT,'YYYY-MM-DD'), TO_CHAR(B.END_DT,'YYYY-MM-DD'), D.DESCR, 
 D.PC_SCH_FIELD1, D.PC_SCH_FIELD2, D.ACTIVITY_USER1, D.PERCENT_COMPLETE, A.EMPLID, F.LAST_NAME, F.FIRST_NAME, A.PRICED_RATE, 
 A.ANALYSIS_TYPE, A.RESOURCE_TYPE, A.RESOURCE_CATEGORY, A.RESOURCE_SUB_CAT, TO_CHAR(A.TRANS_DT,'YYYY-MM-DD'), 
 A.EX_DOC_ID, A.RESOURCE_QUANTITY, A.RESOURCE_AMOUNT, A.TIME_SHEET_ID, A.ACCOUNT, A.DEPTID, A.OPERATING_UNIT, A.PRODUCT, 
 A.FUND_CODE, A.CLASS_FLD, A.CHARTFIELD1, A.CHARTFIELD2, A.CHARTFIELD3, B.PROJECT_ID, D.ACTIVITY_ID, A.PROCESS_INSTANCE,
 B.BUSINESS_UNIT,D.BUSINESS_UNIT,D.PROJECT_ID 
  FROM PS_PROJ_RESOURCE A, PS_PROJECT B, PS_PROJECT_DESCR C, PS_PROJ_ACTIVITY D, PS_PROJECT_TEAM E, PS_PERSONAL_DATA F 
  WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT 
     AND A.PROJECT_ID = B.PROJECT_ID
     AND A.PROCESS_INSTANCE = 36756
     AND A.ANALYSIS_TYPE IN ('TLX','ACT','BIL') 
     AND A.ANALYSIS_TYPE NOT IN ('BIL')
     AND B.BUSINESS_UNIT = C.BUSINESS_UNIT 
     AND B.PROJECT_ID = C.PROJECT_ID 
     AND A.BUSINESS_UNIT = D.BUSINESS_UNIT 
     AND A.PROJECT_ID = D.PROJECT_ID 
     AND A.ACTIVITY_ID = D.ACTIVITY_ID 
     AND A.BUSINESS_UNIT = E.BUSINESS_UNIT 
     AND A.PROJECT_ID = E.PROJECT_ID 
     AND E.TEAM_MEMBER = A.EMPLID 
     AND F.EMPLID = A.EMPLID; 
     
     
     SELECT * FROM PS_CA_ACCTG_LN_PC WHERE PROJECT_ID = '000000000000308'
     
     SELECT * FROM PS_RUN_CNTL_PC_AE WHERE OPRID = 'VAYALLU'
     AND RUN_CNTL_ID LIKE '%LOAD'
     
     DELETE FROM PS_RUN_CNTL_PC_AE WHERE OPRID = 'VAYALLU'
     AND RUN_CNTL_ID LIKE '%LOAD'