SELECT A.ANALYSIS_TYPE, A.* FROM PS_PROJ_RESOURCE A
WHERE A.PROJECT_ID = '000000000000002' 
AND A.ACTIVITY_ID = '000000000000001' 
--AND A.RESOURCE_ID = '10000017'
ORDER BY A.TRANS_DT DESC ;

UPDATE PS_INTFC_PROJ_RES SET RESOURCE_ID = '19999999'
WHERE PROJECT_ID = '000000000000002' 
AND ACTIVITY_ID = '000000000000001' ;
ORDER BY A.TRANS_DT DESC ;

SELECT A.ANALYSIS_TYPE, A.* FROM PS_PROJ_RESOURCE A
WHERE A.PROJECT_ID = '000000000000002' 
AND A.ACTIVITY_ID = '000000000000001' ;

-- Project - Exclusion of project status and % complete for Projects 
SELECT A.PROJECT_ID, A.DESCR, A.PROJECT_TYPE, B.DESCR254, A.PROJECT_USER1,
A.PROJECT_USER2 as Capitalization_Flag, A.START_DT, A.END_DT FROM PS_PROJECT A, PS_PROJECT_DESCR B
WHERE A.BUSINESS_UNIT = 'PC001'
AND A.DESCR like 'OPT_UPK_PROJ01%'
--AND A.PROJECT_ID = '000000000000185'
AND A.BUSINESS_UNIT = B.BUSINESS_UNIT
AND A.PROJECT_ID = B.PROJECT_ID;

-- Activity 
SELECT B.ACTIVITY_ID, B.DESCR, A.START_DT, A.END_DT,
B.START_DT, B.END_DT,B.PERCENT_COMPLETE, B.PC_SCH_FIELD1, B.ACTIVITY_USER1,
B.ACTIVITY_USER2
FROM PS_PROJECT A, PS_PROJ_ACTIVITY B
WHERE A.BUSINESS_UNIT = 'PC001'
--AND A.DESCR = 'OPT_0409013_02'
AND A.PROJECT_ID = '000000000000196'
AND A.BUSINESS_UNIT = B.BUSINESS_UNIT
AND A.PROJECT_ID = B.PROJECT_ID;

--Project team
SELECT B.TEAM_MEMBER, B.BILL_RATE, C.NAME
FROM PS_PROJECT A, PS_PROJECT_TEAM B, PS_PERSONAL_DATA C
WHERE A.BUSINESS_UNIT = 'PC001'
--AND A.DESCR = 'OPT_0409013_02'
AND A.PROJECT_ID = '000000000000309'
AND A.BUSINESS_UNIT = B.BUSINESS_UNIT
AND A.PROJECT_ID = B.PROJECT_ID
AND B.TEAM_MEMBER = C.EMPLID;

-- Project resource data
SELECT B.PROCESS_INSTANCE,B.PRICED_RATE,B.ANALYSIS_TYPE, B.RESOURCE_TYPE, B.RESOURCE_CATEGORY, B.RESOURCE_SUB_CAT,
B.TRANS_DT,B.EX_DOC_ID,B.RESOURCE_QUANTITY,B.PRICED_RATE, B.RESOURCE_AMOUNT,B.FOREIGN_AMOUNT, B.TIME_SHEET_ID,B.ACCOUNT,
B.DEPTID, B.OPERATING_UNIT, B.PRODUCT, B.FUND_CODE, B.CLASS_FLD, B.CHARTFIELD1,B.CHARTFIELD2, B.CHARTFIELD3
 FROM PS_PROJ_RESOURCE B, PS_PROJECT A
WHERE A.BUSINESS_UNIT = 'PC001'
--AND A.DESCR = 'OPT_UPK_PROJ01'
AND A.PROJECT_ID = 'PCCAPROJ'
AND A.BUSINESS_UNIT = B.BUSINESS_UNIT
AND A.PROJECT_ID = B.PROJECT_ID
AND B.ANALYSIS_TYPE = 'TLX';

SELECT B.* FROM PS_PROJ_RESOURCE B, PS_PROJECT A
WHERE A.BUSINESS_UNIT = 'PC001'
--AND A.DESCR = 'OPT_0409013_02'
AND A.PROJECT_ID in ('PCCAPROJ') 
AND A.BUSINESS_UNIT = B.BUSINESS_UNIT
AND A.PROJECT_ID = B.PROJECT_ID;





-- Contracts
SELECT * FROM PS_CA_DETAIL_PROJ
WHERE BUSINESS_UNIT_PC = 'PC001' 
AND CONTRACT_NUM = 'CON000000001114'
AND PROJECT_ID = '000000000000273';
AND ACTIVITY_ID = '000000000000001';

SELECT * FROM PS_PROJECT

SELECT process_instance, a.* FROM PS_CA_ACCTG_LN_PC a
WHERE CONTRACT_NUM in ('CON000000000326','CON000000000328') 
--AND PROCESS_INSTANCE = 13882
AND PROJECT_ID = '000000000000196';

UPDATE PS_CA_DETAIL SET CA_TXN_SOURCE = 'FPC'
WHERE CONTRACT_NUM = 'CON000000005375'
AND CA_TXN_SOURCE = 'CRM';

-- Contracts update SQLs

UPDATE PS_CA_CONTR_HDR SET CA_PROC_STATUS = 'A', CA_STATUS = 'BOOKED'
WHERE CONTRACT_NUM = 'CON000000005375';

UPDATE PS_CA_BILL_PLAN SET BP_STATUS = 'RDY'
WHERE CONTRACT_NUM = 'CON000000005375'AND PLAN_CONTR_ACT = 'Y';

--UPDATE PS_CA_BILL_PLAN SET PROCESS_INSTANCE = 0
SELECT * FROM PS_CA_BILL_PLAN
WHERE CONTRACT_NUM = 'CON000000001114 'AND PLAN_CONTR_ACT = 'Y' AND PROCESS_INSTANCE <> 0;

SELECT SUM(FOREIGN_AMOUNT) FROM PS_PROJ_RESOURCE A
WHERE A.BUSINESS_UNIT = 'PC001'
AND A.PROJECT_ID = '000000000000204'
AND A.ANALYSIS_TYPE = 'BIL';

SELECT * FROM PS_PERSONAL_DATA
UPDATE PS_CA_BI_PC_TA26 SET PRICED_RATE = 1
WHERE DESCR = 'Billable amount - Time Sheet'


UPDATE PS_CA_BI_PC_TA26 SET UNIT_AMT = ROUND(((((PRICED_RATE) * ( 
RATE_MULT))) / ( RATE_DIV)), 2) WHERE (BILL_CUR_OPT = 'D' AND 
PROCESS_INSTANCE = 20953) AND BI_CURRENCY_CD = 'USD'

UPDATE PS_CA_BI_PC_TA26 SET UNIT_AMT = ROUND(((((PRICED_RATE) * 
( RATE_MULT))) / ( R ATE_DIV)), :1) WHERE (BILL_CUR_OPT = 'D' AND 
PROCESS_INSTANCE = 22143) AND BI_CURRENCY_CD = :2 


SELECT * FROM PS_CA_BI_PC_TA26

SELECT * FROM PS_CA_CONTR_HDR
WHERE CONTRACT_NUM LIKE  '%180%';

SELECT * FROM PS_PROJ_RESOURCE
WHERE PROJECT_ID IN ('000000000000263','000000000000264','000000000000265','000000000000266')
AND RATE_DIV = 1
AND analysis_type = 'BIL'

SELECT * FROM PS_PROJ_RESOURCE
WHERE PROcess_instance = 22916;

SELECT * FROM PS_OPR_DEF_TBL_PC
WHERE OPRID IN ('VAYALLU', 'MVINAYAG');

JECT_ID IN ('000000000000263','000000000000264','000000000000265','000000000000266')
AND RATE_DIV = 1
AND analysis_type = 'BIL'


CURRENCY_CD
FOREIGN_CURRENCY

SELECT * FROM PS_PROJ_RESOURCE
WHERE PROJECT_ID IN ('000000000000267')
--AND RATE_DIV = 0
AND analysis_type = 'BIL'


SELECT VW.FROM_CUR , VW.TO_CUR , VW.RT_TYPE , 
TO_CHAR(VW.EFFDT,'YYYY-MM-DD') , VW.RATE_MULT , VW.RATE_DIV , 
TO_CHAR(((VW.EFFDT) + ( -1)),'YYYY-MM-DD') FROM PS_RT_DFLT_VW VW , 
PS_PC_RT_SEL_TAO4 SEL WHERE SEL.PROCESS_INSTANCE = 21974 AND SEL.FROM_CUR = 
VW.FROM_CUR AND SEL.TO_CUR = VW.TO_CUR AND SEL.RT_TYPE = VW.RT_TYPE ORDER BY 
VW.FROM_CUR, VW.TO_CUR, VW.RT_TYPE, VW.EFFDT ASC

SELECT * FROM PS_RT_RATE_TBL

SELECT * FROM PS_CA_BILL_PLAN
WHERE CONTRACT_NUM = 'CON000000000994'AND PLAN_CONTR_ACT = 'Y';

SELECT * FROM PS_CA_ACCTPLAN



AND TRANS_DT = '26-MAR-13';

SELECT * FROM PSSPA_EMAIL_WRK
SELECT * FROM PS_BI_HDR
WHERE INVOICE LIKE '%205';

SELECT * FROM PS_CA_BILL_PLAN
WHERE CONTRACT_NUM LIKE '%180' ;

-- To release the run control id or billing interface id to get processed again 
DELETE FROM PS_INTFC_BI_PROC
WHERE RUN_CNTL_ID = 123