--------------Upside--------------

SELECT * FROM PS_OPTCA_UPCLN_TBL  where contract_num='CON000000002066'
SELECT * FROM PS_OPT_CA_CONT_LN where contract_num='CON000000000171'
SELECT * FROM PS_OPT_CA_LINE where contract_num='CON000000000171'
SELECT * FROM PS_OPT_CONT_HDR

SELECT contract_num,optca_slsevnt,OPT_CA_ARRNGMENTID FROM PS_OPT_CA_ADLN_TBL where contract_num='CON000000000171'
AND  optca_slsevnt ='A'

SELECT contract_num,optca_slsevnt,OPT_CA_ARRNGMENTID,OPT_OPPORNTY_URLID,OPTCA_PROPOSALID,PRODUCT_ID
 FROM PS_OPT_CA_ADLN_TBL where   optca_slsevnt ='A' AND contract_num='CON000000000171'

SELECT * FROM PS_OPT_CA_CONT_LN
SELECT * FROM PS_OPT_CA_LINE
SELECT * FROM PS_OPT_CONT_HDR
