-- Products
SELECT EXTRACT(YEAR FROM DATETIME_ADDED) "Year", EXTRACT(month FROM DATETIME_ADDED) "Month", COUNT(*) FROM PS_PROD_ITEM
GROUP BY EXTRACT(YEAR FROM DATETIME_ADDED) , EXTRACT(month FROM DATETIME_ADDED) 
ORDER BY 1, 2 ;

-- Customers
SELECT EXTRACT(YEAR FROM DATE_LAST_MAINT) "Year", EXTRACT(month FROM DATE_LAST_MAINT) "Month", COUNT(*) FROM PS_CUST_CRSPD A
GROUP BY EXTRACT(YEAR FROM DATE_LAST_MAINT) , EXTRACT(month FROM DATE_LAST_MAINT)
ORDER BY 1, 2 ;

SELECT COUNT(*) FROM PS_CUSTOMER ;

-- Contracts
SELECT EXTRACT(YEAR FROM CONTRACT_SIGN_DT) "Year", EXTRACT(month FROM CONTRACT_SIGN_DT) "Month", COUNT(*), SUM(CONTR_NET_AMT) FROM PS_CA_CONTR_HDR 
GROUP BY EXTRACT(YEAR FROM CONTRACT_SIGN_DT) , EXTRACT(month FROM CONTRACT_SIGN_DT) 
ORDER BY 1, 2 ;

SELECT EXTRACT(YEAR FROM ACCOUNTING_DT) "Year", EXTRACT(month FROM ACCOUNTING_DT) "Month", COUNT(DISTINCT CONTRACT_NUM), SUM(-1*AMOUNT) FROM PS_CA_ACCTG_LINE
WHERE DST_USE = 'REV'
AND CLASS_FLD = '41860' 
GROUP BY EXTRACT(YEAR FROM ACCOUNTING_DT) , EXTRACT(month FROM ACCOUNTING_DT) 
ORDER BY 1, 2 ;

-- Invoices
SELECT EXTRACT(YEAR FROM INVOICE_DT) "Year", EXTRACT(month FROM INVOICE_DT) "Month", COUNT(*), SUM(A.INVOICE_AMOUNT) FROM PS_BI_HDR A
WHERE A.BILL_STATUS = 'INV'
AND A.BILL_TO_MEDIA IN ('A', 'P','M')
GROUP BY EXTRACT(month FROM INVOICE_DT), EXTRACT(YEAR FROM INVOICE_DT) 
order by 1,2;

SELECT EXTRACT(YEAR FROM IVC_PRINTED_DT) "Year", EXTRACT(month FROM IVC_PRINTED_DT) "Month", COUNT(*), SUM(A.INVOICE_AMOUNT) FROM PS_BI_HDR A
WHERE A.BILL_STATUS = 'INV'
AND A.BILL_TO_MEDIA IN ('A', 'P','M')
GROUP BY EXTRACT(month FROM IVC_PRINTED_DT), EXTRACT(YEAR FROM IVC_PRINTED_DT) 
order by 1,2;

-- Items
SELECT EXTRACT(YEAR FROM ASOF_DT) "Year", EXTRACT(month FROM ASOF_DT) "Month", COUNT(*), SUM(A.USER_AMT1) FROM PS_ITEM A
GROUP BY EXTRACT(month FROM ASOF_DT), EXTRACT(YEAR FROM ASOF_DT) 
order by 1,2;

-- Payments
SELECT EXTRACT(YEAR FROM ENTRY_DT) "Year", EXTRACT(month FROM ENTRY_DT) "Month", COUNT(*), SUM(A.PAYMENT_AMT) FROM PS_PAYMENT A 
GROUP BY EXTRACT(YEAR FROM ENTRY_DT) , EXTRACT(month FROM ENTRY_DT) 
ORDER BY 1, 2 ;

-- Projects
SELECT EXTRACT(YEAR FROM FMS_DTTM_STAMP) "Year", EXTRACT(month FROM FMS_DTTM_STAMP) "Month", COUNT(*) FROM PS_PROJECT
GROUP BY EXTRACT(YEAR FROM FMS_DTTM_STAMP) , EXTRACT(month FROM FMS_DTTM_STAMP) 
ORDER BY 1, 2 ;

-- Customer cross refernce table 
SELECT A.OPT_SOURCE_SYSID, COUNT(*) FROM PS_OPT_CUST_CRSREF A
GROUP BY A.OPT_SOURCE_SYSID ;

SELECT A.ANALYSIS_TYPE,EXTRACT(YEAR FROM TRANS_DT) "Year", EXTRACT(month FROM TRANS_DT) "Month", COUNT(*) FROM PS_PROJ_RESOURCE A
WHERE A.ANALYSIS_TYPE IN ('TLX','ACT')
GROUP BY A.ANALYSIS_TYPE,EXTRACT(YEAR FROM TRANS_DT), EXTRACT(month FROM TRANS_DT)
ORDER BY 2, 3;


-- CareTracker Products
SELECT EXTRACT(YEAR FROM DATETIME_ADDED) "Year", EXTRACT(month FROM DATETIME_ADDED) "Month", COUNT(*) FROM PS_PROD_ITEM
WHERE PROD_FIELD_C8 = '41860'
GROUP BY EXTRACT(YEAR FROM DATETIME_ADDED) , EXTRACT(month FROM DATETIME_ADDED) 
ORDER BY 1, 2 ;

SELECT * FROM PS_PROD_ITEM ;
SELECT * FROM PS_OPT_PROD_CRSREF 
WHERE OPT_PR_TAXGL_BU = '41860' ;

-- Customers
SELECT EXTRACT(YEAR FROM DATE_LAST_MAINT) "Year", EXTRACT(month FROM DATE_LAST_MAINT) "Month", COUNT(*) FROM PS_CUST_CRSPD A
GROUP BY EXTRACT(YEAR FROM DATE_LAST_MAINT) , EXTRACT(month FROM DATE_LAST_MAINT)
ORDER BY 1, 2 ;

SELECT * FROM PS_CUSTOMER ;

-- Contracts
SELECT EXTRACT(YEAR FROM CONTRACT_SIGN_DT) "Year", EXTRACT(month FROM CONTRACT_SIGN_DT) "Month", COUNT(*), SUM(CONTR_NET_AMT) FROM PS_CA_CONTR_HDR 
GROUP BY EXTRACT(YEAR FROM CONTRACT_SIGN_DT) , EXTRACT(month FROM CONTRACT_SIGN_DT) 
ORDER BY 1, 2 ;

SELECT * FROM PS_CA_CONTR_HDR

-- Invoices
SELECT EXTRACT(YEAR FROM INVOICE_DT) "Year", EXTRACT(month FROM INVOICE_DT) "Month", COUNT(*), SUM(A.INVOICE_AMOUNT) FROM PS_BI_HDR A
WHERE A.BILL_STATUS = 'INV'
AND A.BILL_TO_MEDIA IN ('A', 'P','M')
AND A.USER6 = '41860'
GROUP BY EXTRACT(month FROM INVOICE_DT), EXTRACT(YEAR FROM INVOICE_DT) 
order by 1,2;

-- Items
SELECT EXTRACT(YEAR FROM A.ASOF_DT) "Year", EXTRACT(month FROM A.ASOF_DT) "Month", COUNT(*), SUM(A.USER_AMT1) FROM PS_ITEM A, PS_BI_HDR B
WHERE B.BILL_STATUS = 'INV'
AND B.BILL_TO_MEDIA IN ('A', 'P','M')
AND B.USER6 = '41860'
AND B.INVOICE = A.ITEM
GROUP BY EXTRACT(month FROM A.ASOF_DT), EXTRACT(YEAR FROM A.ASOF_DT) 
order by 1,2;

-- Payments
SELECT EXTRACT(YEAR FROM A.ASOF_DT) "Year", EXTRACT(month FROM A.ASOF_DT) "Month", COUNT(*), SUM(A.PAYMENT_AMT) FROM PS_ITEM_ACTIVITY A, PS_BI_HDR B
WHERE B.BILL_STATUS = 'INV'
AND B.BILL_TO_MEDIA IN ('A', 'P','M')
AND B.USER6 = '41860'
AND B.INVOICE = A.ITEM
AND A.ENTRY_TYPE = 'PY'
GROUP BY EXTRACT(month FROM A.ASOF_DT), EXTRACT(YEAR FROM A.ASOF_DT) 
order by 1,2;

SELECT * FROM PS_ITEM_ACTIVITY
WHERE ENTRY_TYPE = 'PY' ;

-- Projects
SELECT EXTRACT(YEAR FROM FMS_DTTM_STAMP) "Year", EXTRACT(month FROM FMS_DTTM_STAMP) "Month", COUNT(*) FROM PS_PROJECT
GROUP BY EXTRACT(YEAR FROM FMS_DTTM_STAMP) , EXTRACT(month FROM FMS_DTTM_STAMP) 
ORDER BY 1, 2 ;
