SELECT A.INVOICE, COUNT(*) FROM PS_BI_LINE A 
WHERE A.PPRC_PROMO_CD = 'CRM'
GROUP BY A.INVOICE ;

SELECT A.INVOICE, A.CONTRACT_NUM, A.CONTRACT_LINE_NUM, A.ADJ_LINE_TYPE, A.QTY, A.UNIT_AMT, A.CHARGE_FROM_DT, A.CHARGE_TO_DT, A.* FROM PS_BI_LINE A
WHERE A.INVOICE IN ('0001000059','0001000035') ;

--Production Invoices - 0001000035

SELECT COUNT(*) FROM PS_BI_LINE A
WHERE A.CHARGE_FROM_DT IS NULL ;

SELECT COUNT(*) FROM PS_BI_LINE A
WHERE A.CHARGE_FROM_DT IS NOT NULL ;

SELECT COUNT(*) FROM PS_BI_LINE A ;