SELECT * FROM PS_ITEM
WHERE ITEM_STATUS = 'O'
AND BAL_AMT < 0 ;

SELECT * FROM PS_ITEM
WHERE ITEM_STATUS = 'O'
AND ITEM LIKE 'OA-%' ;

SELECT * FROM PS_ITEM
WHERE ITEM_STATUS = 'O'
AND CUST_ID = '0000000378'