SELECT B.XLATLONGNAME, A.* FROM PS_INTFC_BI A, PSXLATITEM B
WHERE A.LOAD_STATUS_BI = 'ERR'
AND B.FIELDNAME = 'ERROR_STATUS_BI' 
AND A.ERROR_STATUS_BI = B.FIELDVALUE
AND A.INTFC_ID = 154

-- Invalid Bill to Contact - 0080
SELECT * FROM PS_INTFC_BI
WHERE INTFC_ID = 154;

UPDATE PS_INTFC_BI SET CNTCT_SEQ_NUM = 4
WHERE INTFC_ID = 154;

-- Invalid Customer - 0060
SELECT * FROM PS_INTFC_BI
WHERE INTFC_ID = 154;

UPDATE PS_INTFC_BI SET BILL_TO_CUST_ID = '55558'
WHERE INTFC_ID = 154;

SELECT * FROM PS_BI_LINE
WHERE INVOICE = '0001000970' ;

SELECT INVOICE, COUNT(*) FROM PS_BI_LINE
WHERE USER_AMT1 <> 0 
GROUP BY INVOICE
HAVING COUNT(*) > 10 ;