SELECT * FROM PS_OPT_CST_TBL_DTL WHERE OPT_CST_PROG_NAME = 'OPT_AR_SHPAY' AND OPT_CST_CHAR1 = 'INVOICE_REMIT_TO' AND OPT_CST_CHAR6 IN ('OPISIGHT','OHIO');

SELECT * FROM PS_OPT_CST_TBL_DTL WHERE OPT_CST_PROG_NAME = 'OPT_AR_SHPAY' AND OPT_CST_CHAR1 = 'SHORT_PAY_REMIT_TO' AND OPT_CST_CHAR6 IN ('OPISIGHT','OHIO');

SELECT * FROM PS_OPT_CST_TBL_DTL WHERE OPT_CST_PROG_NAME = 'OPT_AR_SHPAY' AND OPT_CST_CHAR6 IN ('OPISIGHT','OHIO');

SELECT * FROM PS_OPT_CST_TBL_DTL WHERE OPT_CST_PROG_NAME = 'OPT_BI_IVCEX' AND OPT_CST_CHAR1 = 'TAX_LINE_DISPLAY_OPTION';



SELECT * FROM PS_CA_DETAIL_PROJ WHERE PROJECT_ID = '010000000000555' ;

SELECT DISTINCT CONTRACT_NUM, CONTRACT_LINE_NUM,ACTIVITY_ID, RES_USER4 FROM PS_PROJ_RESOURCE WHERE PROJECT_ID = '010000000000555' ;

SELECT * FROM PS_OPT_PC_RULE_HDR WHERE PROJECT_ID = '010000000000555' ;

