-- Total number of customers for statements 
SELECT CUST_ID, COUNT(*)
FROM PS_ITEM
WHERE ITEM_STATUS = 'O'
GROUP BY CUST_ID ;
-- 
SELECT DISTINCT A.CUST_ID, A. COMM_METHOD, A.EMAILID FROM PS_CUST_CONTACT A, PS_CUST_CNTCT_DOC B
WHERE A.CUST_ID IN ( SELECT DISTINCT B.CUST_ID FROM PS_ITEM B WHERE B.ITEM_STATUS = 'O')  
AND A.EFFDT = (SELECT MAX(A1.EFFDT) FROM PS_CUST_CONTACT A1 WHERE A1.CUST_ID = A.CUST_ID AND A1.EFF_STATUS = 'A')
AND A.CNTCT_SEQ_NUM = (SELECT MAX(A2.CNTCT_SEQ_NUM) FROM PS_CUST_CONTACT A2 WHERE A2.CUST_ID = A.CUST_ID AND A2.EFFDT = A.EFFDT AND  A2.EFF_STATUS = 'A')
--AND A.CUST_ID = B.CUST_ID 
--AND A.CUST_ID = '0000000346'
AND A.EMAILID  ' ' 

SELECT * FROM PS_CUST_CNTCT_DOC
WHERE CUST_ID = '0000000346';

