Contact:
SELECT CONTACT_ID, REFERENCE_NUM,OPT_SFDC_ID,OPT_SOURCE_SYSID FROM PS_OPT_CONT_CRSREF WHERE REFERENCE_NUM IN (
SELECT REFERENCE_NUM FROM PS_OPT_DC_GCNT_LD WHERE FILENAME LIKE 'CONTACTSDATA_OPT_CONV_2016-05-06%')
ORDER BY CONTACT_ID DESC

Customer:
SELECT CUST_ID, REFERENCE_NUM,OPT_SFDC_ID,OPT_SOURCE_SYSID FROM PS_OPT_CUST_CRSREF WHERE REFERENCE_NUM IN (
SELECT REFERENCE_NUM FROM PS_OPT_DC_GCUST_LD WHERE FILENAME LIKE 'CUSTOMERSDATA_OPT_CONV_2016-05-06%')
ORDER BY CUST_ID DESC

Contact & Customer Linking:
SELECT A.OPT_SFDC_ID as Customer_SFDC , A.REFERENCE_NUM AS customer_Ref_Num, B.OPT_SFDC_ID as Contact_SFDC,
B.Reference_num as Contact_Ref_Num,C.CONTACT_ID,C.CUST_ID from PS_OPT_CS_CONT_LD C,PS_OPT_CUST_CRSREF A, PS_OPT_CONT_CRSREF B
WHERE A.CUST_ID=C.CUST_ID
AND B.CONTACT_ID=C.CONTACT_ID
AND A.OPT_SOURCE_SYSID='OISF'
AND C.FILENAME LIKE 'CONTACTSDATA_OPT_CONV_2016-05-06%';

