SELECT CUST_ID,ACTION_STATUS,CONDITION_ID,CANCEL_REASON_CD,DATE_ADDED,ACTION_DT,COMPLETION_DATE,DUE_DT,
ACTION_CODE,ACTION_PARM,ANCHOR_AMOUNT,last_maint_dttm,last_maint_oprid,ACTION_OWNER,PROPOSED_AUTOMATED,
PROCESSED_FLG,PROCESS_INSTANCE,COND_ROLE 
FROM PS_ACTION_LST 
WHERE CUST_ID IN ('0000000315') 
--AND ANCHOR_AMOUNT = '2500'
AND PROCESS_INSTANCE = 1631
ORDER BY DATE_ADDED,DUE_DT,LAST_MAINT_DTTM,anchor_amount ASC ;

SELECT * FROM PS_ACTION_LST
WHERE CUST_ID IN ('CORETEST1','CORETEST1') ;

-- AR Item details
SELECT A.ITEM, A.CUST_ID, A.DUE_DT,A.ACCOUNTING_DT, A.BAL_AMT, A.ITEM_STATUS FROM PS_ITEM A
WHERE A.CUST_ID IN ('CORETEST1','CORETEST2','CORETEST9','KEYTEST7','KEYTEST8')
ORDER BY ITEM ;

-- Billing invoice details
SELECT A.INVOICE, A.BILL_TO_CUST_ID, A.BILL_STATUS,A.BI_APPROVAL_STATUS, A.INVOICE_DT, A.PYMNT_TERMS_CD, A.DUE_DT,A.ACCOUNTING_DT, A.INVOICE_AMOUNT
FROM PS_BI_HDR A
WHERE A.BILL_TO_CUST_ID IN ('CORETEST1','CORETEST2','CORETEST9','KEYTEST7','KEYTEST8') 
--AND INVOICE IN ('0001002112','0001002117','0001002118');
ORDER BY INVOICE_DT, INVOICE;


SELECT A.ITEM, A.DUE_DT,A.ACCOUNTING_DT, A.* FROM PS_PENDING_ITEM A
WHERE A.ITEM IN ('0001002116','0001002117','0001002118');

--UPDATE PS_ITEM SET DUE_DT = '11-MAR-14'
WHERE ITEM IN ('0001002134') ;

--UPDATE PS_BI_HDR SET DUE_DT = '11-MAR-14', INVOICE_DT = '11-MAR-14', ACCOUNTING_DT = '11-MAR-14'
WHERE INVOICE IN ('0001002134') ;



SELECT A.* FROM PS_CUSTOMER A
WHERE A.CUST_STATUS = 'A'
AND A.CUST_ID NOT IN (SELECT DISTINCT B.CUST_ID FROM PS_ITEM B
WHERE B.ITEM_STATUS = 'O');

SELECT * FROM PS_DUN_CUST 
WHERE CRSPD_CUST_ID IN ('CORETEST1','CORETEST2') ;

SELECT * FROM PS_BI_HDR
WHERE INVOICE = '0001002115'