SELECT BILL_STATUS, COUNT(*) FROM PS_BI_HDR 
GROUP BY BILL_STATUS ;

SELECT DISTINCT USER6 FROM PS_BI_HDR ;
SELECT DISTINCT USER3 FROM PS_BI_LINE ; 

SELECT DISTINCT CONTRACT_NUM FROM PS_CA_CONTR_HDR 
ORDER BY CONTRACT_NUM;

SELECT LAST_AUTO_NBR, MAX_LENGTH FROM PS_AUTO_NUM_TBL WHERE NUM_TYPE = 'CONT' ;
SELECT LAST_AUTO_NBR, MAX_LENGTH FROM PS_AUTO_NUM_TBL WHERE NUM_TYPE = 'RNW' ;
SELECT LAST_PROJECT_ID, LAST_RESOURCE_ID FROM PS_INSTALLATION_PC ;

SELECT MAX(CONTRACT_NUM) FROM PS_CA_CONTR_HDR
WHERE CONTRACT_NUM BETWEEN 'CON000000000001' AND 'CON000000005000' ;

SELECT MAX(CONTRACT_NUM) FROM PS_CA_CONTR_HDR
WHERE CONTRACT_NUM BETWEEN 'CON000000005001' AND 'CON999999999999' ;


SELECT  * FROM PS_EOAW_STEPINST WHERE EOAWPRCS_ID = :1 AND EOAWDEFN_ID = :2 AND EFFDT = TO_DATE(:3,'YYYY-MM-DD') ;
SELECT  * FROM PS_EOAW_STEPINST WHERE EOAWPRCS_ID = 'Test Invoice Approval';

SELECT MAX(PROJECT_ID) FROM PS_PROJECT WHERE PROJECT_ID LIKE '%000%';
SELECT DISTINCT RESOURCE_ID FROM PS_PROJ_RESOURCE ;

-- Last Project ID
SELECT MAX(PROJECT_ID) FROM PS_PROJECT WHERE PROJECT_ID LIKE '%000%';

SELECT RESOURCE_ID FROM PS_PROJ_RESOURCE;

SELECT * FROM PS_AUTO_NUM_TBL WHERE NUM_TYPE = 'CONT' ;

SELECT PROJECT_ID FROM PS_PROJECT 

SELECT LAST_PROJECT_ID, LAST_RESOURCE_ID FROM PS_INSTALLATION_PC ;

SELECT DISPLAY_LENGTH 
  FROM PS_FS_CF_TEMPLATE 
 WHERE FIELDNAME = 'PROJECT_ID';


