SELECT * FROM PS_PROJECT

SELECT * FROM PS_PROJECT_DESCR WHERE PROJECT_ID LIKE 'H%'

SELECT  TRUNC(SYSDATE) FROM DUAL;

SELECT SYSDATE FROM DUAL

SELECT * FROM PS_PERSONAL_DATA WHERE TRUNC(SYNCDTTM) = '12/15/2015'

select * from PS_PERSONAL_DATA where EXTRACT(YEAR FROM TO_DATE(SYNCDTTM,'DD/MM/YYYY'))

TRUNC(TO_DATE('01/01/2011 00:00:00','DD/MM/YYYY HH24:MI:SS'));

select EXTRACT(DAY FROM SYNCDTTM),SYNCDTTM FROM PS_PERSONAL_DATA 

SELECT A.*,TRUNC(SYNCDTTM) FROM  PS_PERSONAL_DATA A
where TRUNC(SYNCDTTM) = '1/20/2015'

SELECT TRUNC(SYNCDTTM), A.* FROM  PS_PERSONAL_DATA A

ALTER SESSION SET nls_date_format='DD-MON-YYYY HH24:MI:SS';

SELECT * FROM PS_PERSONAL_DATA WHERE TRUNC(SYNCDTTM) = TO_DATE('27/04/2013','DD/MM/YYYY');

SELECT * FROM PS_PERSONAL_DATA WHERE TRUNC(SYNCDTTM) = '27/04/2013'

SELECT * FROM PS_PERSONAL_DATA WHERE TRUNC(SYNCDTTM) = TO_DATE('14/12/2015','DD/MM/YYYY');

SELECT SYSDATE,LAST_DAY(SYSDATE) FROM   dual;


======================


SELECT * FROM ps_customer WHERE TRUNC(date_last_maint) > TO_DATE('23/03/2016','DD/MM/YYYY')
and LAST_MAINT_OPRID <>'OPT_CONV';

SELECT * FROM PS_CONTACT WHERE TRUNC(date_last_maint) > TO_DATE('23/03/2016','DD/MM/YYYY')
and LAST_MAINT_OPRID <>'OPT_CONV';


Working - 


select * from PS_PROD_ITEM WHERE TRUNC(datetime_added) = '20-DEC-2016'
ORDER BY PRODUCT_ID

select * from PS_PROD_ITEM WHERE TRUNC(lastupddttm) = '20-DEC-2016'
ORDER BY PRODUCT_ID
