SELECT A.ANALYSIS_TYPE, A.BI_DISTRIB_STATUS, COUNT(*)
FROM PS_PROJ_RESOURCE A
WHERE A.RESOURCE_TYPE = 'LABOR' 
AND A.RESOURCE_SUB_CAT = 'BILL'
AND A.ANALYSIS_TYPE IN ('TLX','BIL','BLD','WTO','DEF','OLT')
AND A.BI_DISTRIB_STATUS NOT IN ('N')
AND A.RES_USER1 = ' '
GROUP BY A.ANALYSIS_TYPE, A.BI_DISTRIB_STATUS ;

SELECT A.ANALYSIS_TYPE, A.BI_DISTRIB_STATUS, COUNT(*)
FROM PS_PROJ_RESOURCE A
WHERE A.RESOURCE_TYPE = 'LABOR'
AND A.RESOURCE_SUB_CAT = 'BILL' 
AND A.ANALYSIS_TYPE IN ('TLX','BIL','BLD','WTO','DEF','OLT')
AND A.BI_DISTRIB_STATUS NOT IN ('N')
AND A.RES_USER1 <> ' '
GROUP BY A.ANALYSIS_TYPE, A.BI_DISTRIB_STATUS ; 

SELECT A.INVOICE, COUNT(*) FROM PS_BI_LINE A, PS_BI_HDR B
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT
AND A.INVOICE = B.INVOICE
AND B.BILL_STATUS = 'INV'
--AND A.USER8 <> ' '
AND A.RESOURCE_TYPE = 'LABOR' 
AND A.RESOURCE_SUB_CAT = 'BILL'
GROUP BY A.INVOICE ;

SELECT COUNT(*) FROM PS_BI_LINE A, PS_BI_HDR B
WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT
AND A.INVOICE = B.INVOICE
AND B.BILL_STATUS = 'INV'
AND A.USER8 = ' '
AND A.RESOURCE_TYPE = 'LABOR' ;






 
