 SELECT A.BUSINESS_UNIT, A.INVOICE, A.BILL_TYPE_ID, A.BILL_STATUS, A.BILL_TO_MEDIA, A.INVOICE_AMOUNT, TO_CHAR(A.INVOICE_DT,'YYYY-MM-DD'), TO_CHAR(A.DUE_DT,'YYYY-MM-DD'), A.IVC_PRINTED_FLG, TO_CHAR(A.IVC_PRINTED_DT,'YYYY-MM-DD'), A.ATT_IVC_IMG_FLG 
  FROM PS_BI_HDR A 
  WHERE ( A.BILL_TO_MEDIA = 'P' 
     AND A.BILL_STATUS IN ('FNL','INV') 
     AND A.IVC_PRINTED_FLG = 'Y' ) 