-- 413 Invoices
SELECT * FROM PS_ITEM
WHERE ITEM_STATUS = 'O'
AND DUE_DT IN ('16-OCT-13', '17-OCT-13');

-- Core 262, Key 99, Strategic 52
SELECT B.CUSTOMER_GROUP, COUNT(*) FROM PS_ITEM A, PS_CUST_CGRP_LNK B 
WHERE A.ITEM_STATUS = 'O'
AND A.DUE_DT IN ('10-DEC-13')
AND A.CUST_ID = B.CUST_ID
GROUP BY B.CUSTOMER_GROUP ;

-- Distinct customers 191
SELECT DISTINCT A.CUST_ID FROM PS_ITEM A, PS_CUST_CGRP_LNK B 
WHERE A.ITEM_STATUS = 'O'
AND A.DUE_DT IN ('16-OCT-13', '17-OCT-13')
AND A.CUST_ID = B.CUST_ID
AND B.CUSTOMER_GROUP = 'CORE';

-- 117 email ids
SELECT a.* FROM PS_ITEM A, PS_CUST_CGRP_LNK B, PS_CUST_CONTACT C
WHERE A.ITEM_STATUS = 'O'
AND A.DUE_DT IN ('16-OCT-13', '17-OCT-13')
AND A.CUST_ID = B.CUST_ID
AND B.CUSTOMER_GROUP = 'CORE'
AND A.CUST_ID = C.CUST_ID
AND C.COMM_METHOD IN ('P','E');
AND C.EMAILID <> ' ' ;

-- Due date 23 Oct, 24 Oct
SELECT DISTINCT A.DUE_DT + 7 FROM PS_ITEM A, PS_CUST_CGRP_LNK B 
WHERE A.ITEM_STATUS = 'O'
AND A.DUE_DT IN ('16-OCT-13', '17-OCT-13')
AND A.CUST_ID = B.CUST_ID
AND B.CUSTOMER_GROUP = 'CORE' ; 

SELECT * FROM PS_ACTION_LST 
WHERE PROPOSED_AUTOMATED = 'A'
AND COMPLETION_DATE = '10-DEC-13'
AND ACTION_CODE = 'DLTR';



SELECT * FROM PS_CUST_CGRP_LNK;
SELECT DISTINCT COMM_METHOD FROM PS_CUST_CONTACT WHERE EMAILID <> ' ' ;
SELECT * FROM PS_CONTACT_CUST;

SELECT DISTINCT A.BILL_TO_CUST_ID FROM PS_BI_HDR A, PSXLATITEM B
WHERE A.INVOICE_DT IN ('16-SEP-13', '17-SEP-13')
--AND A.ACCOUNTING_DT IN ('15-OCT-13', '16-OCT-13')
AND B.FIELDNAME = 'BILL_TO_MEDIA'
AND B.EFF_STATUS = 'A'
AND B.FIELDVALUE = A.BILL_TO_MEDIA
AND A.BILL_STATUS = 'INV'
AND A.BILL_TO_MEDIA IN ('A') ;
--AND A.INVOICE BETWEEN  '0001000121' AND '0001000179'

