SELECT DISTINCT TO_CHAR(A.DUN_DT,'YYYY-MM-DD'), A.CRSPD_CUST_ID, A.BUSINESS_UNIT, A.CUST_ID, A.NAME1, A.ITEM, A.DUN_SEQ_NUM, A.NAMESHORT, A.ENTRY_TYPE, A.ENTRY_REASON, TO_CHAR(A.DUE_DT,'YYYY-MM-DD'), TO_CHAR(A.ACCOUNTING_DT,'YYYY-MM-DD'), A.BAL_AMT, A.BAL_CURRENCY, A.BAL_AMT_LAST, A.DSP_CUR_CD_WSH, A.DAYS_LATE, A.REMIT_ADDRESS1, A.REMIT_ADDRESS2, A.REMIT_ADDRESS3, A.REMIT_ADDRESS4, A.REMIT_CITY, A.REMIT_NUM1, A.REMIT_NUM2, A.REMIT_HOUSE_TYPE, A.REMIT_IN_CITY_LMT, A.REMIT_COUNTY, A.REMIT_STATE, A.REMIT_GEO_CODE, A.REMIT_POSTAL, E.DESCR, A.REMIT_PHONE, A.ADDRESS1, A.ADDRESS2, A.ADDRESS3, A.ADDRESS4, A.CITY, A.NUM1, A.NUM2, A.HOUSE_TYPE, A.COUNTY, A.STATE, A.POSTAL, A.GEO_CODE, A.IN_CITY_LIMIT, F.DESCR, A.CNTCT_NAME1, A.DESCRSHORT, A.CLCT_NAME, A.ITEM_LINE, A.LANGUAGE_CD, D.DUN_ID_NUM, D.RUN_CNTL_ID, D.OPRID, A.FC_AMT, A.FC_AMT_DSP, A.LC_AMT, A.LC_AMT_DSP, A.INCLUDE_FC, A.INCLUDE_DC, A.DELIVERY_METHOD, A.FAX, A.EMAILID, A.PRINTER, A.ASSN_OPRID, C.DUN_TEXT, G.PO_REF, I.PHONE, I.FAX, I.TITLE, I.EXT_EMAIL_ADDR, B.NAME1, B.NAME2, B.NAME3, B.NAME4, B.NAMESPACE, B.TITLE,E.COUNTRY,F.COUNTRY 
  FROM (PS_AR33000_TMP A LEFT OUTER JOIN  PS_OPT_AR_NAME_VW B ON  A.CUST_ID = B.CUST_ID ), PS_DUN_CUST C, PS_AR_DUNNING_REQ D, PS_COUNTRY_TBL E, PS_COUNTRY_TBL F, PS_ITEM G, PS_CUST_OPTION H, PS_COLLECTOR_TBL I 
  WHERE ( D.OPRID = 'VAYALLU' 
    AND ( A.CRSPD_SETID = C.CRSPD_SETID 
     AND A.CRSPD_CUST_ID = C.CRSPD_CUST_ID 
     AND A.DUN_ID_NUM = C.DUN_ID_NUM 
     AND A.DUN_ID_NUM = D.DUN_ID_NUM 
     AND E.COUNTRY = A.COUNTRY 
     AND F.COUNTRY = A.REMIT_COUNTRY 
     AND A.BUSINESS_UNIT = G.BUSINESS_UNIT 
     AND A.CUST_ID = G.CUST_ID 
     AND A.ITEM = G.ITEM 
     AND A.ITEM_LINE = G.ITEM_LINE 
     AND A.CUST_ID = H.CUST_ID 
     AND H.EFFDT = 
        (SELECT MAX(H_ED.EFFDT) FROM PS_CUST_OPTION H_ED 
        WHERE H.SETID = H_ED.SETID 
          AND H.CUST_ID = H_ED.CUST_ID 
          AND H_ED.EFFDT <= SYSDATE) 
     AND H.SETID = I.SETID 
     AND I.COLLECTOR = H.COLLECTOR 
     AND I.EFFDT = 
        (SELECT MAX(I_ED.EFFDT) FROM PS_COLLECTOR_TBL I_ED 
        WHERE I.SETID = I_ED.SETID 
          AND I.COLLECTOR = I_ED.COLLECTOR 
          AND I_ED.EFFDT <= SYSDATE) 
     AND C.LETTER_CD = '1' 
     AND D.RUN_CNTL_ID = :2 
     AND D.OPRID = :1 
     AND A.AG_PRINT_FLAG <> 'Y' ) ) 
  ORDER BY 2, 3, 4, 6, 50