SELECT A.CUST_ID, A.ACTION_STATUS,A.ANCHOR_AMOUNT, B.ITEM, B.BAL_AMT,B.ITEM_STATUS, C.BILL_TO_MEDIA, D.CUSTOMER_GROUP, A.* 
FROM PS_ACTION_LST A, PS_ITEM B, PS_BI_HDR C, PS_CUST_CGRP_LNK D
WHERE A.ASSN_OPRID = 'MCHAMBER'
AND A.ACTION_CODE = 'DLTR'
--AND DELIVERY_METHOD = 'E'
AND ACTION_STATUS IN ('NEW')
AND A.DUE_DT = '24-OCT-13'
AND A.CUST_ID = B.CUST_ID
AND A.ANCHOR_AMOUNT = B.BAL_AMT 
AND B.ITEM = C.INVOICE 
AND A.CUST_ID = D.CUST_ID;

SELECT * FROM PS_ACTION_LST 
WHERE ACTION_CODE = 'DLTR'
AND DELIVERY_METHOD = 'E'
--AND ACTION_STATUS IN ('NEW')
AND DUE_DT = '24-OCT-13';

SELECT * FROM PS_ACTION_LST WHERE CUST_ID = '0000000421'
SELECT * FROM PS_ITEM WHERE CUST_ID = '0000000129'

SELECT ACTION_STATUS, ACTION_DT, DUE_DT,CUST_ID, COUNT(*) FROM PS_ACTION_LST WHERE ACTION_CODE = 'DLTR'
GROUP BY ACTION_STATUS,ACTION_DT, DUE_DT, CUST_ID  ;

SELECT * FROM PS_ITEM
WHERE CUST_ID = '0000000103'

SELECT * FROM PS_ACTION_LST 
WHERE CUST_ID = '0000000339' ;

SELECT A.CUSTOMER_GROUP, COUNT(*) FROM PS_CUST_CGRP_LNK A, PS_CUSTOMER B
WHERE A.CUST_ID = B.CUST_ID
AND B.CUST_STATUS = 'A'
GROUP BY CUSTOMER_GROUP;

SELECT COUNT(*) FROM PS_CUSTOMER WHERE CUST_STATUS = 'A';

SELECT * FROM PS_CUSTOMER ;

SELECT * FROM PS_ACTION_LST 
WHERE ACTION_CODE = 'DLTR'
AND DELIVERY_METHOD = 'E'
AND ACTION_STATUS NOT IN ('CMP','SCA','SYS')
AND ACTION_DT = '24-OCT-13';

select action_status, count(*) from PS_ACTION_LST where  Action_code = 'DLTR' and  PRoPOSED_AUTOMATED = 'A'  /* and CUST_ID = '0000000129'*/
 group by action_status



select cust_id, action_dt, proposed_automated, tmplt_id from ps_action_lst where action_status not in ('CMP','SCA' ) and action_code='DLTR'  and action_parm='1'
order by cust_id

