SELECT A.ENTRY_USE_ID, B.ENTRY_TYPE, L.DESCR, B.ENTRY_REASON, B.DESCR, I.DEBIT_CREDIT, 'System Defined' 
  FROM PS_AUTO_REASON_TBL A, PS_ENTRY_REASN_TBL B, PS_AUTO_ENTRY_TBL C, PS_ENTRY_USE_L_TBL I, PS_ENTRY_TYPE_TBL L 
  WHERE ( A.EFFDT = 
        (SELECT MAX(A_ED.EFFDT) FROM PS_AUTO_REASON_TBL A_ED 
        WHERE A.SETID = A_ED.SETID 
          AND A.ENTRY_USE_ID = A_ED.ENTRY_USE_ID 
          AND A_ED.EFFDT <= SYSDATE) 
     AND A.SETID = B.SETID 
     AND A.ENTRY_REASON = B.ENTRY_REASON 
     AND A.SETID = C.SETID 
     AND A.ENTRY_USE_ID = C.ENTRY_USE_ID 
     AND C.EFFDT = 
        (SELECT MAX(C_ED.EFFDT) FROM PS_AUTO_ENTRY_TBL C_ED 
        WHERE C.SETID = C_ED.SETID 
          AND C.ENTRY_USE_ID = C_ED.ENTRY_USE_ID 
          AND C_ED.EFFDT <= SYSDATE) 
     AND A.ENTRY_USE_ID = I.ENTRY_USE_ID 
     AND B.ENTRY_TYPE = C.ENTRY_TYPE 
     AND B.SETID = L.SETID 
     AND B.ENTRY_TYPE = L.ENTRY_TYPE ) 
UNION 
SELECT E.ENTRY_USE_ID, F.ENTRY_TYPE, K.DESCR, F.ENTRY_REASON, F.DESCR, D.DEBIT_CREDIT, 'User Defined' 
  FROM PS_AUTO_REASON_TBL E, PS_ENTRY_REASN_TBL F, PS_AUTO_ENTRY_TBL G, PS_ENTRY_TYPE_TBL K, PS_AUTO_LINES_TBL D 
  WHERE E.EFFDT = 
        (SELECT MAX(E_ED.EFFDT) FROM PS_AUTO_REASON_TBL E_ED 
        WHERE E.SETID = E_ED.SETID 
          AND E.ENTRY_USE_ID = E_ED.ENTRY_USE_ID 
          AND E_ED.EFFDT <= SYSDATE) 
     AND E.SETID = F.SETID 
     AND E.ENTRY_REASON = F.ENTRY_REASON 
     AND E.SETID = G.SETID 
     AND E.ENTRY_USE_ID = G.ENTRY_USE_ID 
     AND G.EFFDT = 
        (SELECT MAX(G_ED.EFFDT) FROM PS_AUTO_ENTRY_TBL G_ED 
        WHERE G.SETID = G_ED.SETID 
          AND G.ENTRY_USE_ID = G_ED.ENTRY_USE_ID 
          AND G_ED.EFFDT <= SYSDATE) 
     AND F.ENTRY_TYPE = G.ENTRY_TYPE 
     AND F.SETID = K.SETID 
     AND F.ENTRY_TYPE = K.ENTRY_TYPE 
     AND E.SETID = D.SETID 
     AND E.ENTRY_USE_ID = D.ENTRY_USE_ID 
     AND E.ENTRY_REASON = D.ENTRY_REASON 
     AND D.EFFDT = 
        (SELECT MAX(D_ED.EFFDT) FROM PS_AUTO_LINES_TBL D_ED 
        WHERE D.SETID = D_ED.SETID 
          AND D.ENTRY_USE_ID = D_ED.ENTRY_USE_ID 
          AND D_ED.EFFDT <= SYSDATE) 
  ORDER BY 1, 2, 4, 6, 7