SELECT * FROM PSPRUFDEFN
WHERE OPRID = 'PC_User1';

DELETE FROM PSPRUFDEFN
WHERE OPRID = 'Invoicetest';

INSERT INTO PSPRUFDEFN
SELECT PORTAL_NAME, 'Invoicetest', PORTAL_REFTYPE, PORTAL_LABEL, 

