SELECT *
  FROM ps_bi_hdr_note n 
 WHERE n.note_type='PROJECT'

UPDATE PS_BI_LINE A 
SET A.USER8 = 
(SELECT B.RES_USER1 FROM PS_PROJ_RESOURCE B 
WHERE A.RESOURCE_TYPE = 'FIXED'
AND A.BUSINESS_UNIT_PC = B.BUSINESS_UNIT
AND A.PROJECT_ID = B.PROJECT_ID
AND A.ACTIVITY_ID = B.ACTIVITY_ID
AND A.RESOURCE_ID = B.RESOURCE_ID)
WHERE EXISTS
(SELECT 'X' FROM PS_PROJ_RESOURCE B
WHERE A.RESOURCE_TYPE = 'FIXED'
AND A.BUSINESS_UNIT_PC = B.BUSINESS_UNIT
AND A.PROJECT_ID = B.PROJECT_ID
AND A.ACTIVITY_ID = B.ACTIVITY_ID
AND A.RESOURCE_ID = B.RESOURCE_ID);


UPDATE ps_bi_line l 
  SET l.user8 = ( 
 SELECT res_user1 
  FROM ps_proj_resource p 
 WHERE p.business_unit=l.business_unit_pc 
   AND p.project_id=l.project_id 
   AND p.activity_id=l.activity_id 
   AND p.resource_id=l.resource_id) 

SELECT * FROM PS_BI_HDR_NOTE
WHERE  NOTE_TYPE = 'PROJECT'


SELECT * FROM PS_BI_HDR
WHERE --RESOURCE_TYPE = 'EXPEN' 
PROJECT_ID <> ' ' ;

SELECT A.RES_USER1, A.* FROM PS_PROJ_RESOURCE A
WHERE A.PROJECT_ID = '000000000000033'
AND A.ANALYSIS_TYPE IN ('BIL', 'TLX','ACT')
AND A.RESOURCE_TYPE = 'FIXED' ;