SELECT A.INVOICE, A.INVOICE_LINE, A.QTY, A.UNIT_AMT AS INVOICE_AMT, A.USER_AMT1 AS UNIT_PRICE, A.NET_EXTENDED_AMT,
 A.PRODUCT_ID FROM PS_BI_LINE A, PS_PROD_ITEM B
WHERE A.PRODUCT_ID = B.PRODUCT_ID
AND B.PRICING_STRUCTURE = 'AMT'
--AND A.PRODUCT_ID LIKE '%35'; 
AND A.INVOICE > '0001005000'
ORDER BY A.INVOICE ;

-- Fixed fee product with $0 as line amount
SELECT A.INVOICE, A.INVOICE_LINE, A.QTY, A.UNIT_AMT AS INVOICE_AMT, A.USER_AMT1 AS UNIT_PRICE, A.NET_EXTENDED_AMT,
 A.PRODUCT_ID FROM PS_BI_LINE A, PS_PROD_ITEM B
WHERE A.PRODUCT_ID = B.PRODUCT_ID
AND B.PRICING_STRUCTURE = 'AMT'
AND A.NET_EXTENDED_AMT = 0
--AND A.PRODUCT_ID LIKE '%35'; 
--AND A.INVOICE > '0001005000'
ORDER BY A.INVOICE ;

SELECT DISTINCT PRICING_STRUCTURE
FROM PS_PROD_ITEM ;