SELECT * FROM PS_ITEM
WHERE ITEM_STATUS = 'O' ;

SELECT INVOICE, COUNT(*) FROM PS_BI_LINE
WHERE TAX_AMT <> 0
--AND INVOICE > '0001000956' 
GROUP BY INVOICE ;

SELECT A.BAL_CURRENCY, A.BAL_AMT_BASE,A.CURRENCY_CD, A.ORIG_ITEM_AMT,A.BAL_AMT, A.USER_AMT1,A.ORIG_ITEM_AMT-A.USER_AMT1, A.* FROM PS_ITEM A WHERE A.ITEM = '0001000675' ;

SELECT A.TOT_SU_TAX, A.BASE_CURRENCY,A.INVOICE_AMT_BSE, A.BI_CURRENCY_CD, A.INVOICE_AMOUNT, A.* FROM PS_BI_HDR A WHERE A.INVOICE = '0001000675' ;

SELECT A.* FROM PS_ITEM_DST A WHERE A.ITEM = '0001000675' ;

SELECT A.* FROM PS_BI_LINE A WHERE A.INVOICE = '0001000675' ;

SELECT A.* FROM PS_BI_LINE_DS_DTL A WHERE A.INVOICE = '0001000675' ;