SET ECHO ON;
SET TIME ON;
SPOOL C:\Users\sselv35\PS\Datamover\psqdv03.LOG

INSERT INTO PS_PRCSRUNCNTL (OPRID,RUN_CNTL_ID,LANGUAGE_CD,LANGUAGE_OPTION) VALUES ('OPT_BATCH','OPT_BATCH_DAILY_AM','ENG','O');
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS) 
VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','ARAUTOMT','OPT_BATCH','OPT_BATCH_DAILY_PM','AUTOMNT_REQ_OPT','ACCOUNTING_DT','C','N','A'); 
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS)
 VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','ARUPDATE','OPT_BATCH','OPT_BATCH_DAILY_GL','POSTING_REQUEST','POST_TO_DT','C','N','A'); 
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS)
 VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','ARUPDATE','OPT_BATCH','OPT_BATCH_DAILY_RECURR','POSTING_REQUEST','POST_TO_DT','C','N','A');
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS)
 VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','CA_BI_INTFC','OPT_BATCH','OPT_BATCH_MONTHLY_GL_1st','RUN_CNTL_CA_AE','BILL_THRU_DATE','C','Y','A');
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS)
 VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','CA_BI_INTFC','OPT_BATCH','OPT_BATCH_MONTHLY_GL_1st','RUN_CNTL_CA_AE','INVOICE_DT','C','Y','A'); 
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS)
 VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','CA_BI_INTFC','OPT_BATCH','OPT_BATCH_MONTHLY_GL_15_2','RUN_CNTL_CA_AE','BILL_THRU_DATE','C','Y','A');
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS)
 VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','CA_BI_INTFC','OPT_BATCH','OPT_BATCH_MONTHLY_GL_15_2','RUN_CNTL_CA_AE','INVOICE_DT','C','Y','A'); 
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS)
 VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','CA_BI_INTFC','OPT_BATCH','OPT_BATCH_MONTHLY_GL_15th','RUN_CNTL_CA_AE','BILL_THRU_DATE','C','Y','A');
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS)
 VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','CA_BI_INTFC','OPT_BATCH','OPT_BATCH_MONTHLY_GL_15th','RUN_CNTL_CA_AE','INVOICE_DT','C','Y','A'); 
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS)
 VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','CA_BI_INTFC','OPT_BATCH','OPT_BATCH_DAILY_GL_PC','RUN_CNTL_CA_AE','BILL_THRU_DATE','C','Y','A');
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS)
 VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','CA_BI_INTFC','OPT_BATCH','OPT_BATCH_DAILY_GL_PC','RUN_CNTL_CA_AE','EVENT_DT','C','Y','A'); 
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS)
 VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','CA_BI_INTFC','OPT_BATCH','OPT_BATCH_DAILY_GL_PC','RUN_CNTL_CA_AE','INVOICE_DT','C','Y','A'); 
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS) 
VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','CA_BI_INTFC','OPT_BATCH','OPT_BATCH_DAILY_GL_TXN','RUN_CNTL_CA_AE','BILL_THRU_DATE','C','Y','A'); 
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS) 
VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','CA_BI_INTFC','OPT_BATCH','OPT_BATCH_DAILY_GL_TXN','RUN_CNTL_CA_AE','EVENT_DT','C','Y','A'); 
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS) 
VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','CA_BI_INTFC','OPT_BATCH','OPT_BATCH_DAILY_GL_TXN','RUN_CNTL_CA_AE','INVOICE_DT','C','Y','A'); 
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS) 
VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','CA_LOAD_DEF','OPT_BATCH','OPT_BATCH_DAILY_GL_DR','RUN_CNTL_CA_AE','THRU_DATE','C','Y','A'); 
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS) 
VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','CA_LOAD_GL1','OPT_BATCH','OPT_BATCH_DAILY_GL','RUN_CNTL_CA_AE','THRU_DATE','C','Y','A'); 
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS) 
VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','CA_RNW_PRCS','OPT_BATCH','OPT_BATCH_DAILY_PM','RUN_CNTL_CA_AE','EVENT_DT','C','Y','A'); 
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS)
 VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','FS_CEBD','OPT_BATCH','OPT_BATCH_DAILY_AM','COMBO_BLD_REQ','AS_OF_DATE','C','N','A'); 
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS)
 VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','OPTARCMN','OPT_BATCH','OPT_BATCH_DAILY_PM','AR_RUNCNTL_CM','ANCHOR_DATE','C','N','A'); 
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS)
 VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','OPT_ARST','OPT_BATCH','OPT_BATCH_MONTHLY','RUN_CNTL_AR','AS_OF_DATE','C','N','A'); 
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS) 
VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','OPT_AR_ACCTG','OPT_BATCH','OPT_BATCH_DAILY_GL','POSTING_REQUEST','POST_TO_DT','C','N','A'); 
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS) 
VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','OPT_AR_ACCTG','OPT_BATCH','OPT_BATCH_DAILY_RECURR','POSTING_REQUEST','POST_TO_DT','C','N','A'); 
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS) 
VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','PSA_ACCTGGL','OPT_BATCH','OPT_BATCH_DAILY_GL','RUN_CNTL_CA_AE','OVERRIDE_ACCTG_DT','C','Y','A'); 
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS) 
VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','PSA_ACCTGGL','OPT_BATCH','OPT_BATCH_DAILY_GL','RUN_CNTL_CA_AE','THRU_DATE','C','Y','A'); 
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS) 
VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','PSA_ACCTGGL','OPT_BATCH','OPT_BATCH_DAILY_GL_PC','RUN_CNTL_CA_AE','OVERRIDE_ACCTG_DT','C','Y','A'); 
/
INSERT INTO PS_OPT_BT_UPD_RNCT (RUN_CNTL_ID,OPRID,PRCSNAME,OPRID2,RUN_CNTL_ID2,RECNAME,FIELDNAME,OPT_DATE_UPD,OPT_PRCS_KEY,STATUS) 
VALUES ('OPT_BATCH_DAILY_AM','OPT_BATCH','PSA_ACCTGGL','OPT_BATCH','OPT_BATCH_DAILY_GL_PC','RUN_CNTL_CA_AE','THRU_DATE','C','Y','A');
/

COMMIT;
/

SPOOL OFF;
EXIT