SELECT A.INVOICE, COUNT(*) FROM PS_BI_LINE A, PS_BI_LINE_TAX B
WHERE A.TAX_AMT <> 0 
--AND INVOICE > 0001009093 
AND A.INVOICE = B.INVOICE
AND A.LINE_SEQ_NUM = B.LINE_SEQ_NUM
AND B.TAX_DIVISION <> '43421'
AND A.TAX_AMT > 0
GROUP BY A.INVOICE
HAVING COUNT(*) = 1
ORDER BY INVOICE ;

--SIT, PRODUCT 000000000000000135, Original invoice - 0001000583, ACR 0001012947, ARB 0001012948

-- 0001012832 - ACR - Header adjustment credit; doesn't make a call during proforma and calls vertex during finalizatio, passes original invoice dt to tax_calc_dt
-- 0001012833 - ARB - Header adjustment rebill; makes a call during proforma and finalization
-- 0001012837 - ADJ - Line create net adjustment only
-- 0001012838 - ACR and ARB - Line reversal and rebill
-- 0001012838 - ACR - Credit line
-- Header INVOICE_TYPE, Line ADJ_LINE_TYPE
SELECT A.INVOICE, B.LINE_SEQ_NUM, B.ADJ_LINE_TYPE, A.ORIGINAL_INVOICE,  A.BILL_TO_CUST_ID, B.PRODUCT_ID, A.INVOICE_AMT_PRETAX, B.TAX_AMT, A.INVOICE_AMOUNT,A.CONTRACT_NUM, A.BILL_STATUS,B.ADJ_LINE_TYPE, B.FINAL_TAX_FLG, B.* FROM PS_BI_HDR A, PS_BI_LINE B
WHERE A.INVOICE IN ('0001013050','0001012749','0001012749') AND A.INVOICE = B.INVOICE 
ORDER BY A.INVOICE, B.LINE_SEQ_NUM ;

SELECT * FROM PS_BI_HDR A
WHERE A.ORIGINAL_INVOICE = '0001009655' ;

SELECT A.INVOICE, A.INVOICE_TYPE, A.ORIGINAL_INVOICE,  A.BILL_TO_CUST_ID,A.INVOICE_AMT_PRETAX, A.INVOICE_AMOUNT FROM PS_BI_HDR A
WHERE A.ORIGINAL_INVOICE <> A.INVOICE ;

SELECT A.INVOICE, A.LINE_SEQ_NUM, A.ACCOUNTING_DT, A.ACCT_ENTRY_TYPE, A.ACCOUNTING_PERIOD, A.FISCAL_YEAR, A.ACCOUNT, A.OPERATING_UNIT, A.CLASS_FLD,
A.MONETARY_AMOUNT, A.* FROM PS_BI_ACCT_ENTRY A
WHERE A.INVOICE IN ('0001003467','0001013045','0001013046') 
ORDER BY A.INVOICE ;

SELECT A.* FROM PS_CA_ACCTG_LN_TXN A
WHERE A.CONTRACT_NUM = 'CON000000000221'  
AND ACCT_PLAN_ID = 'R101' ;

SELECT A.* FROM PS_CA_ACCTG_LINE A
WHERE A.CONTRACT_NUM = 'CON000000000221'
AND ACCT_PLAN_ID = 'R101' ;



SELECT * FROM PS_BI_HDR a
WHERE CONTRACT_NUM = 'CON000000001079' ;

SELECT INVOICE, COUNT(*) FROM PS_BI_LINE
WHERE TAX_AMT <> 0
GROUP BY INVOICE
HAVING COUNT(*) = 1;

SELECT * FROM PS_BI_LINE
WHERE INVOICE = '0001000905' 

SELECT A.INVOICE, A.CONTRACT_NUM, A.* FROM PS_BI_HDR A
WHERE A.INVOICE = '0001012833' ;

SELECT A.INVOICE, A.BILL_STATUS, A.INVOICE_AMOUNT, A. CONTRACT_NUM, A.INVOICE_TYPE,A.ORIGINAL_INVOICE, A.* FROM PS_BI_HDR A
WHERE A.CONTRACT_NUM = 'CON000000000258' ;

SELECT * FROM PS_CA_BP_XREF


SELECT A.INVOICE, A.PRODUCT_ID, B.TAX_DIVISION, A.CONTRACT_NUM, A.CONTRACT_LINE_NUM, COUNT(*) FROM PS_BI_LINE A, PS_BI_LINE_TAX B
WHERE A.TAX_AMT <> 0 
--AND INVOICE > 0001009093 
AND A.INVOICE = B.INVOICE
AND A.LINE_SEQ_NUM = B.LINE_SEQ_NUM
AND B.TAX_DIVISION <> '43421'
AND A.TAX_AMT > 0
GROUP BY A.INVOICE, A.PRODUCT_ID, B.TAX_DIVISION, A.CONTRACT_NUM, A.CONTRACT_LINE_NUM
HAVING COUNT(*) = 1
ORDER BY INVOICE ;