SELECT BILL_STATUS, COUNT(*) FROM PS_BI_HDR
WHERE INVOICE_DT <> ACCOUNTING_DT 
GROUP BY BILL_STATUS ;

SELECT A.INVOICE_DT, A.ACCOUNTING_DT, A.DUE_DT, A.* FROM PS_BI_HDR A
WHERE A.INVOICE_DT <> ACCOUNTING_DT ;


SELECT COUNT(*) FROM PS_ITEM A
WHERE A.INVOICE_DT <> A.ASOF_DT 
AND A.BUSINESS_UNIT = 'AR003' ;

SELECT A.INVOICE_DT, A.ACCOUNTING_DT, A.DUE_DT, A.ASOF_DT, A.POST_DT, A.* FROM PS_ITEM A
WHERE A.INVOICE_DT <> A.ASOF_DT ;

SELECT A.INVOICE_DT, A.ACCOUNTING_DT, A.DUE_DT, A.ASOF_DT, A.POST_DT, A.* FROM PS_ITEM A
WHERE A.INVOICE_DT <> A.ASOF_DT ;
--WHERE A.ITEM = '0001006342' ;

SELECT * FROM PS_BI_HDR
WHERE INVOICE = '0001004420' ;

SELECT A.* FROM PS_BI_ACCT_ENTRY A
WHERE A.INVOICE = '0001006342' ;


SELECT A.BUSINESS_UNIT, COUNT(*) FROM PS_ITEM A
WHERE A.INVOICE_DT <> A.ASOF_DT 
GROUP BY A.BUSINESS_UNIT ;

SELECT A.BUSINESS_UNIT, COUNT(*) FROM PS_ITEM A
WHERE A.INVOICE_DT = A.ASOF_DT 
GROUP BY A.BUSINESS_UNIT ;

SELECT BILL_STATUS, COUNT(*) FROM PS_BI_HDR
WHERE INVOICE_DT = ACCOUNTING_DT 
GROUP BY BILL_STATUS ;

SELECT BILL_STATUS, COUNT(*) FROM PS_BI_HDR
WHERE INVOICE_DT <> ACCOUNTING_DT 
GROUP BY BILL_STATUS ;