SELECT * FROM PS_OPT_BI_INV_VW ;

SELECT * FROM PS_OPT_BI_INV_VW ;

SELECT * FROM PS_BI_HDR
WHERE INVOICE BETWEEN '0001000445' AND '0001000450';


SELECT A.BILL_STATUS,A.BI_APPROVAL_STATUS,A.CNTCT_SEQ_NUM, COUNT(*) FROM PS_BI_HDR A
WHERE A.BILL_STATUS IN ('NEW','RDY')
AND A.BI_APPROVAL_STATUS NOT IN (2, 3)
GROUP BY A.BILL_STATUS,A.BI_APPROVAL_STATUS,A.CNTCT_SEQ_NUM;

SELECT A.BILL_STATUS,A.BI_APPROVAL_STATUS, COUNT(*) FROM PS_BI_HDR A
WHERE A.BILL_STATUS IN ('NEW','RDY')
AND A.BI_APPROVAL_STATUS NOT IN (2, 3)
AND A.CNTCT_SEQ_NUM <> 0
GROUP BY A.BILL_STATUS,A.BI_APPROVAL_STATUS;

SELECT A.ROLEUSER, B.OPRDEFNDESC FROM PSROLEUSER A, PSOPRDEFN B
WHERE A.ROLENAME = 'OPT_BI_Invoice_Approver1'
AND A.ROLEUSER = B.OPRID; 

SELECT * FROM PSROLEUSER
WHERE ROLEUSER = 'JJOGUNOO';

SELECT BILL_STATUS, INVOICE_DT, BI_APPROVAL_STATUS, COUNT(*) FROM PS_BI_HDR 
WHERE BILL_STATUS IN ('NEW', 'RDY')
AND INVOICE_DT > '15-NOV-13'
GROUP BY BILL_STATUS, INVOICE_DT, BI_APPROVAL_STATUS ;


 SELECT A.BUSINESS_UNIT, A.INVOICE, A.BI_APPROVAL_STATUS, B.XLATLONGNAME,B.FIELDNAME 
  FROM PS_BI_HDR A, PSXLATITEM B 
  WHERE A.BILL_STATUS IN ('NEW','RDY')
  AND A.BI_APPROVAL_STATUS <> 3 
  AND A.BUSINESS_UNIT = 'BI001' 
  AND B.EFFDT = (SELECT MAX(B_ED.EFFDT) FROM PSXLATITEM B_ED 
        WHERE B.FIELDNAME = B_ED.FIELDNAME 
          AND B.FIELDVALUE = B_ED.FIELDVALUE 
          AND B_ED.EFFDT <= SYSDATE) 
     AND B.FIELDNAME = 'BI_APPROVAL_STATUS' 
     AND A.BI_APPROVAL_STATUS = B.FIELDVALUE  
     
-- View definition
SELECT A.BUSINESS_UNIT 
 , A.INVOICE 
 , A.INVOICE_DT 
 , A.INVOICE_AMOUNT 
 , A.BILL_STATUS 
 , A.BI_APPROVAL_STATUS 
 , A.BILL_TO_CUST_ID 
 , C.NAME1 
 , B.CONTACT_ID 
 , D.NAME1 || ' ' || E.NAMESPACE AS NAME1 
 , A.USER6 
 , A.BILL_BY_ID 
 , A.BILL_CYCLE_ID 
 , A.BILL_TO_MEDIA 
  FROM PS_BI_HDR A 
  , PS_CONTACT_CUST B 
  , PS_CUSTOMER C 
  , PS_CONTACT D 
  , PS_OPT_CONT_CRSREF E 
 WHERE A.PROCESS_INSTANCE = 0 
   AND A.BI_APPROVAL_STATUS NOT IN ('2','3') 
   AND A.BILL_STATUS IN ('NEW','RDY') 
   AND A.INVOICE NOT IN ( 
 SELECT INVTMP.INVOICE 
  FROM PS_OPT_BI_INV_TMP INVTMP 
 WHERE INVTMP.BUSINESS_UNIT = A.BUSINESS_UNIT 
   AND INVTMP.IN_PROCESS_FLG = 'Y') 
   AND C.SETID = ( 
 SELECT SETID 
  FROM PS_SET_CNTRL_REC 
 WHERE RECNAME = 'CUSTOMER' 
   AND SETCNTRLVALUE = A.BUSINESS_UNIT) 
   AND B.SETID = C.SETID 
   AND D.SETID = B.SETID 
   AND E.SETID = B.SETID 
   AND E.CONTACT_ID = B.CONTACT_ID 
   AND D.CONTACT_ID = B.CONTACT_ID 
   AND C.CUST_ID = A.BILL_TO_CUST_ID 
   AND B.CUST_ID = A.BILL_TO_CUST_ID 
   AND B.CNTCT_SEQ_NUM = A.CNTCT_SEQ_NUM 
   AND A.CNTCT_SEQ_NUM <> 0 
   AND B.EFF_STATUS = 'A' 
   AND D.EFF_STATUS ='A' 
   AND %EffdtCheck(CONTACT CONT, D, A.INVOICE_DT) 
   AND %EffdtCheck(CONTACT_CUST CNTCST, B, A.INVOICE_DT) 
  UNION 
 SELECT A.BUSINESS_UNIT 
 , A.INVOICE 
 , A.INVOICE_DT 
 , A.INVOICE_AMOUNT 
 , A.BILL_STATUS 
 , A.BI_APPROVAL_STATUS 
 , A.BILL_TO_CUST_ID 
 , C.NAME1 
 , ' ' 
 , A.NAME1 
 , A.USER6 
 , A.BILL_BY_ID 
 , A.BILL_CYCLE_ID 
 , A.BILL_TO_MEDIA 
  FROM PS_BI_HDR A 
  , PS_CUSTOMER C 
 WHERE A.PROCESS_INSTANCE = 0 
   AND A.BI_APPROVAL_STATUS NOT IN ('2','3') 
   AND A.BILL_STATUS IN ('NEW','RDY') 
   AND A.INVOICE NOT IN ( 
 SELECT INVTMP.INVOICE 
  FROM PS_OPT_BI_INV_TMP INVTMP 
 WHERE INVTMP.BUSINESS_UNIT = A.BUSINESS_UNIT 
   AND INVTMP.IN_PROCESS_FLG = 'Y') 
   AND C.SETID = ( 
 SELECT SETID 
  FROM PS_SET_CNTRL_REC 
 WHERE RECNAME = 'CUSTOMER' 
   AND SETCNTRLVALUE = A.BUSINESS_UNIT) 
   AND C.CUST_ID = A.BILL_TO_CUST_ID 
   AND A.CNTCT_SEQ_NUM = 0