--4657  records - UAR accounting at bill line
SELECT COUNT(*) FROM PS_BI_LINE_DST_UAR;
--4657  records - AR accounting at bill line
SELECT COUNT(*) FROM PS_BI_LINE_DST_AR;
--0  records - Rev accounting at bill line
SELECT COUNT(*) FROM PS_BI_LINE_DST;
--2317 records - AR accounting at bill hdr
SELECT COUNT(*) FROM PS_BI_HDR_AR;

-- 2371 RECORDS, 54 invoices have different UAR strings
SELECT INVOICE,CLASS_FLD, OPERATING_UNIT, ACCOUNT, PRODUCT, COUNT(*) FROM PS_BI_LINE_DST_UAR
GROUP BY INVOICE,CLASS_FLD, OPERATING_UNIT, ACCOUNT, PRODUCT ;

SELECT INVOICE,CLASS_FLD, OPERATING_UNIT, ACCOUNT, PRODUCT, COUNT(*) FROM PS_BI_LINE_DST_UAR
GROUP BY INVOICE,CLASS_FLD, OPERATING_UNIT, ACCOUNT, PRODUCT ;

-- 2317 RECORDS
SELECT COUNT(*) FROM PS_BI_HDR ;

SELECT DISTINCT CLASS_FLD, OPERATING_UNIT, ACCOUNT, PRODUCT FROM PS_BI_LINE_DST_UAR WHERE INVOICE = '0001000078';
SELECT DISTINCT CLASS_FLD, OPERATING_UNIT, ACCOUNT, PRODUCT FROM PS_BI_LINE_DST_AR WHERE INVOICE = '0001000078';
SELECT DISTINCT CLASS_FLD, OPERATING_UNIT, ACCOUNT, PRODUCT FROM PS_BI_HDR_AR WHERE INVOICE = '0001000078';

0001001505