SELECT A.BI_APPROVAL_STATUS, A.* FROM PS_BI_HDR A
WHERE A.INVOICE_AMOUNT > 250000;

SELECT * FROM PSROLEUSER
WHERE ROLENAME LIKE 'OPT_BI_Invoice_Approver1';


SELECT DISTINCT ROLENAME FROM PSROLEUSER
WHERE ROLENAME LIKE 'OPT_BI%';

SELECT * FROM PS_BI_AW_XREF WHERE INVOICE IN ('0001013456','0001013463');
SELECT * FROM PS_EOAW_STEPINST WHERE EOAWTHREAD_ID IN (22521,534,353);
SELECT * FROM PS_EOAW_USERINST WHERE EOAWSTEP_INSTANCE = 791;

SELECT * FROM PS_BI_IVC_AUD_TBL WHERE INVOICE IN ('0001000089','0001000099','0001000135');

SELECT * FROM PS_EOAWCRTA_REC
WHERE EOAWCRTA_ID LIKE '%Credit%';

SELECT * FROM PS_EOAWCRTA
WHERE EOAWCRTA_ID LIKE '%Credit%';

DELETE FROM PS_EOAWCRTA
WHERE EOAWCRTA_ID = 'Path-Credit InvoiceCredit Invoice Approval2013-03-07_stg_10_path_1' ;

SELECT * FROM PS_EOAWCRTA
WHERE EOAWCRTA_ID = 'Path-Credit InvoiceCredit Invoice Approval2013-03-07_stg_10_path_1' ;

DELETE FROM PS_EOAWCRTA_REC
WHERE RECNAME = 'BI_HDR' ;
