 
SELECT /*+ PARALLEL(64) */  A.BUSINESS_UNIT, A.INVOICE, B.INVOICE, B.INVOICE_AMOUNT, A.INVOICE_AMOUNT, TO_CHAR(A.INVOICE_DT,'YYYY-MM-DD'), A.BUSINESS_UNIT_PC, A.PROJECT_ID, A.BILL_TO_CUST_ID, A.BILL_STATUS, A.CONTRACT_NUM, A.BILL_TYPE_ID, A.BILL_CYCLE_ID, TO_CHAR(CAST((A.ADD_DTTM) AS TIMESTAMP),'YYYY-MM-DD-HH24.MI.SS.FF') 
  FROM PS_BI_HDR A, PS_BI_HDR B 
  WHERE ( A.BUSINESS_UNIT = B.BUSINESS_UNIT 
     AND A.INVOICE <> B.INVOICE 
     AND A.BILL_CYCLE_ID = B.BILL_CYCLE_ID 
     AND A.BUSINESS_UNIT_PC = B.BUSINESS_UNIT_PC 
     AND A.CONTRACT_NUM = B.CONTRACT_NUM 
     AND A.PROJECT_ID = B.PROJECT_ID 
     AND A.USER6 = B.USER6 
     AND B.CONTRACT_NUM <> ' ' 
     AND A.INVOICE NOT LIKE 'TMP%' 
     AND B.INVOICE LIKE 'TMP%' 
     AND B.BUSINESS_UNIT = :1 
     AND B.INVOICE BETWEEN Decode(:2, ' ', DECODE(:3, ' ',  B.INVOICE,:3), :2 ) AND Decode(:3, ' ', DECODE(:2, ' ',  B.INVOICE,:2), :3 ) 
     AND A.INVOICE BETWEEN Decode(:6, ' ', DECODE(:7, ' ', A.INVOICE,:7), :6) AND Decode(:7, ' ', DECODE(:6, ' ', A.INVOICE,:6), :7) 
     AND B.CONTRACT_NUM = Decode(:5, ' ',  B.CONTRACT_NUM, :5) 
     AND A.PROJECT_ID <> ' ' 
     AND EXISTS (SELECT 'X' 
  FROM PS_BI_LINE C, PS_BI_LINE D 
  WHERE C.BUSINESS_UNIT = D.BUSINESS_UNIT 
     AND C.INVOICE <> D.INVOICE 
     AND C.BUSINESS_UNIT_CA = D.BUSINESS_UNIT_CA 
     AND C.CONTRACT_NUM = D.CONTRACT_NUM 
     AND C.CONTRACT_LINE_NUM = D.CONTRACT_LINE_NUM 
     AND C.BUSINESS_UNIT_PC = D.BUSINESS_UNIT_PC 
     AND C.PROJECT_ID = D.PROJECT_ID 
     AND C.ACTIVITY_ID = D.ACTIVITY_ID 
     AND C.RESOURCE_ID = D.RESOURCE_ID 
     AND C.RESOURCE_TYPE = D.RESOURCE_TYPE 
     AND C.RESOURCE_CATEGORY = D.RESOURCE_CATEGORY 
     AND C.RESOURCE_SUB_CAT = D.RESOURCE_SUB_CAT 
     AND C.ANALYSIS_TYPE = D.ANALYSIS_TYPE 
     AND C.BUSINESS_UNIT = A.BUSINESS_UNIT 
     AND C.INVOICE = A.INVOICE 
     AND D.BUSINESS_UNIT = B.BUSINESS_UNIT 
     AND D.INVOICE = B.INVOICE) ) 
UNION 
SELECT /*+ PARALLEL(64) */  E.BUSINESS_UNIT, ' ', E.INVOICE, E.INVOICE_AMOUNT, 0, TO_CHAR(E.INVOICE_DT,'YYYY-MM-DD'), E.BUSINESS_UNIT_PC, E.PROJECT_ID, E.BILL_TO_CUST_ID, E.BILL_STATUS, E.CONTRACT_NUM, E.BILL_TYPE_ID, E.BILL_CYCLE_ID, TO_CHAR(CAST((E.ADD_DTTM) AS TIMESTAMP),'YYYY-MM-DD-HH24.MI.SS.FF') 
  FROM PS_BI_HDR E 
  WHERE E.INVOICE LIKE 'TMP%' 
     AND E.CONTRACT_NUM <> ' ' 
     AND E.BUSINESS_UNIT = :1 
     AND E.INVOICE BETWEEN Decode(:2, ' ', DECODE(:3, ' ',  E.INVOICE,:3), :2 ) AND Decode(:3, ' ', DECODE(:2, ' ',  E.INVOICE,:2), :3) 
     AND E.CONTRACT_NUM = Decode(:5, ' ',  E.CONTRACT_NUM, :5) 
     AND E.PROJECT_ID <> ' ' 
     AND ( ' ' = :6 
     AND ' ' = :7) 
     AND NOT EXISTS (SELECT 'X' 
  FROM PS_BI_HDR F 
  WHERE F.INVOICE NOT LIKE 'TMP%' 
     AND E.BUSINESS_UNIT = F.BUSINESS_UNIT 
     AND E.INVOICE <> F.INVOICE 
     AND E.BILL_CYCLE_ID = F.BILL_CYCLE_ID 
     AND E.BUSINESS_UNIT_PC = F.BUSINESS_UNIT_PC 
     AND E.CONTRACT_NUM = F.CONTRACT_NUM 
     AND E.PROJECT_ID = F.PROJECT_ID 
     AND E.USER6 = F.USER6 
     AND EXISTS (SELECT 'X' 
  FROM PS_BI_LINE G, PS_BI_LINE H 
  WHERE G.BUSINESS_UNIT = H.BUSINESS_UNIT 
     AND G.INVOICE <> H.INVOICE 
     AND G.BUSINESS_UNIT_CA = H.BUSINESS_UNIT_CA 
     AND G.CONTRACT_NUM = H.CONTRACT_NUM 
     AND G.CONTRACT_LINE_NUM = H.CONTRACT_LINE_NUM 
     AND G.BUSINESS_UNIT_PC = H.BUSINESS_UNIT_PC 
     AND G.PROJECT_ID = H.PROJECT_ID 
     AND G.ACTIVITY_ID = H.ACTIVITY_ID 
     AND G.RESOURCE_ID = H.RESOURCE_ID 
     AND G.RESOURCE_TYPE = H.RESOURCE_TYPE 
     AND G.RESOURCE_CATEGORY = H.RESOURCE_CATEGORY 
     AND G.RESOURCE_SUB_CAT = H.RESOURCE_SUB_CAT 
     AND G.ANALYSIS_TYPE = H.ANALYSIS_TYPE 
     AND G.BUSINESS_UNIT = E.BUSINESS_UNIT 
     AND G.INVOICE = E.INVOICE 
     AND H.BUSINESS_UNIT = F.BUSINESS_UNIT 
     AND H.INVOICE = F.INVOICE)) 
UNION 
SELECT /*+ PARALLEL(64) */  J.BUSINESS_UNIT, J.INVOICE, ' ', 0, J.INVOICE_AMOUNT, TO_CHAR(J.INVOICE_DT,'YYYY-MM-DD'), J.BUSINESS_UNIT_PC, J.PROJECT_ID, J.BILL_TO_CUST_ID, J.BILL_STATUS, J.CONTRACT_NUM, J.BILL_TYPE_ID, J.BILL_CYCLE_ID, TO_CHAR(CAST((J.ADD_DTTM) AS TIMESTAMP),'YYYY-MM-DD-HH24.MI.SS.FF') 
  FROM PS_BI_HDR J 
  WHERE J.INVOICE NOT LIKE 'TMP%' 
     AND J.CONTRACT_NUM <> ' ' 
     AND J.BUSINESS_UNIT = :1 
     AND J.INVOICE BETWEEN Decode(:6, ' ', DECODE(:7, ' ',  J.INVOICE,:7), :6 ) AND Decode(:7, ' ', DECODE(:6, ' ',  J.INVOICE,:6), :7) 
     AND J.CONTRACT_NUM = Decode(:5, ' ',  J.CONTRACT_NUM, :5) 
     AND J.PROJECT_ID <> ' ' 
     AND ( ' ' = :2 
     AND ' ' = :3) 
     AND NOT EXISTS (SELECT 'X' 
  FROM PS_BI_HDR K 
  WHERE K.INVOICE LIKE 'TMP%' 
     AND J.BUSINESS_UNIT = K.BUSINESS_UNIT 
     AND J.INVOICE <> K.INVOICE 
     AND J.BILL_CYCLE_ID = K.BILL_CYCLE_ID 
     AND J.BUSINESS_UNIT_PC = K.BUSINESS_UNIT_PC 
     AND J.CONTRACT_NUM = K.CONTRACT_NUM 
     AND J.PROJECT_ID = K.PROJECT_ID 
     AND J.USER6 = K.USER6 
     AND EXISTS (SELECT 'X' 
  FROM PS_BI_LINE L, PS_BI_LINE M 
  WHERE L.BUSINESS_UNIT = M.BUSINESS_UNIT 
     AND L.INVOICE <> M.INVOICE 
     AND L.BUSINESS_UNIT_CA = M.BUSINESS_UNIT_CA 
     AND L.CONTRACT_NUM = M.CONTRACT_NUM 
     AND L.CONTRACT_LINE_NUM = M.CONTRACT_LINE_NUM 
     AND L.BUSINESS_UNIT_PC = M.BUSINESS_UNIT_PC 
     AND L.PROJECT_ID = M.PROJECT_ID 
     AND L.ACTIVITY_ID = M.ACTIVITY_ID 
     AND L.RESOURCE_ID = M.RESOURCE_ID 
     AND L.RESOURCE_TYPE = M.RESOURCE_TYPE 
     AND L.RESOURCE_CATEGORY = M.RESOURCE_CATEGORY 
     AND L.RESOURCE_SUB_CAT = M.RESOURCE_SUB_CAT 
     AND L.ANALYSIS_TYPE = M.ANALYSIS_TYPE 
     AND L.BUSINESS_UNIT = J.BUSINESS_UNIT 
     AND L.INVOICE = J.INVOICE 
     AND M.BUSINESS_UNIT = K.BUSINESS_UNIT 
     AND M.INVOICE = K.INVOICE)) 
  ORDER BY 2  