 
SELECT /*+ PARALLEL(64) */ A.BUSINESS_UNIT, A.INVOICE, B.INVOICE, sum( G.NET_EXTENDED_AMT +  G.TAX_AMT), A.INVOICE_AMOUNT, TO_CHAR(A.INVOICE_DT,'YYYY-MM-DD'), A.BUSINESS_UNIT_PC, A.PROJECT_ID, A.BILL_TO_CUST_ID, A.BILL_STATUS, A.CONTRACT_NUM, A.BILL_TYPE_ID, A.BILL_CYCLE_ID, TO_CHAR(CAST((A.ADD_DTTM) AS TIMESTAMP),'YYYY-MM-DD-HH24.MI.SS.FF') 
  FROM PS_BI_HDR A, PS_BI_HDR B, PS_BI_LINE F, PS_BI_LINE G 
  WHERE ( A.BUSINESS_UNIT = B.BUSINESS_UNIT 
     AND A.INVOICE <> B.INVOICE 
     AND A.BILL_CYCLE_ID = B.BILL_CYCLE_ID 
     AND A.BUSINESS_UNIT_PC = B.BUSINESS_UNIT_PC 
     AND A.CONTRACT_NUM = B.CONTRACT_NUM 
     AND A.PROJECT_ID = B.PROJECT_ID 
     AND A.USER6 = B.USER6 
     AND A.BUSINESS_UNIT = F.BUSINESS_UNIT 
     AND A.INVOICE = F.INVOICE 
     AND B.BUSINESS_UNIT = G.BUSINESS_UNIT 
     AND B.INVOICE = G.INVOICE 
     AND F.LINE_SEQ_NUM = G.LINE_SEQ_NUM 
     AND B.CONTRACT_NUM <> ' ' 
     AND A.INVOICE NOT LIKE 'TMP%' 
     AND B.INVOICE LIKE 'TMP%' 
     AND B.BUSINESS_UNIT = :1 
     AND A.INVOICE_AMT_PRETAX = (SELECT sum(net_extended_amt) 
  FROM PS_BI_LINE E 
  WHERE E.ANALYSIS_TYPE = 'BIL' 
     AND E.INVOICE = B.INVOICE 
     AND E.BUSINESS_UNIT = B.BUSINESS_UNIT) 
     AND B.INVOICE BETWEEN Decode(:2, ' ', DECODE(:3, ' ',  B.INVOICE,:3), :2 ) AND Decode(:3, ' ', DECODE(:2, ' ',  B.INVOICE,:2), :3 ) 
     AND A.INVOICE BETWEEN Decode(:6, ' ', DECODE(:7, ' ', A.INVOICE,:7), :6) AND Decode(:7, ' ', DECODE(:6, ' ', A.INVOICE,:6), :7) 
     AND B.CONTRACT_NUM = Decode(:5, ' ',  B.CONTRACT_NUM, :5) 
     AND A.PROJECT_ID <> ' ' 
     AND EXISTS (SELECT 'X' 
  FROM PS_BI_LINE C, PS_BI_LINE D 
  WHERE C.BUSINESS_UNIT = D.BUSINESS_UNIT 
     AND C.INVOICE <> D.INVOICE 
     AND C.BUSINESS_UNIT_CA = D.BUSINESS_UNIT_CA 
     AND C.CONTRACT_NUM = D.CONTRACT_NUM 
     AND C.CONTRACT_LINE_NUM = D.CONTRACT_LINE_NUM 
     AND C.BUSINESS_UNIT_PC = D.BUSINESS_UNIT_PC 
     AND C.PROJECT_ID = D.PROJECT_ID 
     AND C.ACTIVITY_ID = D.ACTIVITY_ID 
     AND C.RESOURCE_ID = D.RESOURCE_ID 
     AND C.RESOURCE_TYPE = D.RESOURCE_TYPE 
     AND C.RESOURCE_CATEGORY = D.RESOURCE_CATEGORY 
     AND C.RESOURCE_SUB_CAT = D.RESOURCE_SUB_CAT 
     AND C.ANALYSIS_TYPE = D.ANALYSIS_TYPE 
     AND C.BUSINESS_UNIT = A.BUSINESS_UNIT 
     AND C.INVOICE = A.INVOICE 
     AND D.BUSINESS_UNIT = B.BUSINESS_UNIT 
     AND D.INVOICE = B.INVOICE) ) 
  GROUP BY  /*+ PARALLEL(64) */ A.BUSINESS_UNIT,  A.INVOICE,  B.INVOICE,  A.INVOICE_AMOUNT,  TO_CHAR(A.INVOICE_DT,'YYYY-MM-DD'),  A.BUSINESS_UNIT_PC,  A.PROJECT_ID,  A.BILL_TO_CUST_ID,  A.BILL_STATUS,  A.CONTRACT_NUM,  A.BILL_TYPE_ID,  A.BILL_CYCLE_ID,  TO_CHAR(CAST((A.ADD_DTTM) AS TIMESTAMP),'YYYY-MM-DD-HH24.MI.SS.FF') 
  ORDER BY 2  