SELECT * FROM PS_PROJ_RESOURCE WHERE PROJECT_ID='000000000000686'
AND RES_USER4='RID0001061'

SELECT PROJECT_ID,ACTIVITY_ID,ANALYSIS_TYPE,RESOURCE_SUB_CAT,FOREIGN_AMOUNT,PROCESS_INSTANCE,
PC_DISTRIB_STATUS,GL_DISTRIB_STATUS,SYSTEM_SOURCE,BI_DISTRIB_STATUS,INVOICE,
RESOURCE_QUANTITY,RESOURCE_AMOUNT,PRICED_RATE FROM PS_PROJ_RESOURCE
WHERE PROJECT_ID='000000000000686'
AND RES_USER4='RID0001062'

SELECT * FROM PSXLATITEM WHERE FIELDNAME='GL_DISTRIB_STATUS';
SELECT * FROM PSXLATITEM WHERE FIELDNAME='PC_DISTRIB_STATUS'
AND FIELDVALUE IN ('C','I')

SELECT * FROM PSXLATITEM WHERE FIELDNAME='SYSTEM_SOURCE'
AND FIELDVALUE IN ('PRP','PRV','PPC')

SELECT * FROM PSXLATITEM WHERE FIELDNAME='BI_DISTRIB_STATUS'
AND FIELDVALUE IN ('PRP','PRV','PPC')

select * from ps_bi_hdr where contract_num='CON000000006049'




