
select COUNT(*) from PS_PRCSDEFN where SERVERNAME='PSUNX'; --62 ROWS
SELECT COUNT(*)  FROM ps_PRCSJOBDEFN where sERVERNAME='PSUNX';--27 ROWS

---Check the trace options 
SELECT PRCSTYPE, PRCSNAME, PARMLISTTYPE, PARMLIST 
FROM PS_PRCSDEFN WHERE PARMLISTTYPE <> 0
AND PRCSTYPE = 'Application Engine'
order by 1,2,3;


----
SELECT * FROM ( SELECT ROWNUM, PRCSINSTANCE,PRCSTYPE, PRCSNAME, TO_CHAR(TRUNC(SYSDATE)+(ENDDTTM-BEGINDTTM),'HH24:MI:SS') EXEC_TIME
FROM   PSPRCSRQST 
WHERE TO_CHAR(TRUNC(SYSDATE)+(ENDDTTM-BEGINDTTM),'HH24:MI:SS') IS NOT NULL
AND PRCSNAME='PC_PRICING'
ORDER BY EXEC_TIME DESC)

----
SELECT * FROM ( SELECT  PRCSINSTANCE,PRCSTYPE, PRCSNAME, RUNDTTM,BEGINDTTM,ENDDTTM, TO_CHAR(TRUNC(SYSDATE)+(ENDDTTM-BEGINDTTM),'HH24:MI:SS') EXEC_TIME
FROM   PSPRCSRQST 
WHERE TO_CHAR(TRUNC(SYSDATE)+(ENDDTTM-BEGINDTTM),'HH24:MI:SS') IS NOT NULL
AND PRCSNAME='OPT_BI_IVCEX'
ORDER BY EXEC_TIME DESC)


WHERE ROWNUM <= 200 ;


SELECT * FROM ( SELECT  PRCSINSTANCE,PRCSTYPE, PRCSNAME,BEGINDTTM,ENDDTTM, TO_CHAR(TRUNC(SYSDATE)+(ENDDTTM-BEGINDTTM),'HH24:MI:SS') EXEC_TIME
FROM   PSPRCSRQST 
WHERE TO_CHAR(TRUNC(SYSDATE)+(ENDDTTM-BEGINDTTM),'HH24:MI:SS') IS NOT NULL
AND PRCSNAME='PC_PRICING'
ORDER BY EXEC_TIME DESC)


--to get active session
PS_BAT_TIMINGS_DTL;
PS_BAT_TIMINGS_FN;
ps_bat_timings_log


Service now Scheduling


select prcsname, parmlist from PS_PRCSDEFN where prcsname in('BIIVC000','AR_UPDATE','AR_PGG1'
,'AR_UPDATE2','BICURCNV','BIPRELD','OPT_BIAR_LD','BI_WRKSHTUPD','AR_PREDICT1','AR_PP1','OPT_CON_INTG','OPT_PC_PRFEE','OPT_PC_PERCT','AR_PAYLOAD','PC_VAR_PRICE','BIIF0001');



--*************************************************************************************
--** Users Who Have Not Logged in Since a Date
--*************************************************************************************
SELECT OPRID,
  OPRDEFNDESC,
  EMAILID
FROM PSOPRDEFN A
WHERE NOT EXISTS
  (SELECT 'x'
  FROM PSACCESSLOG B
  WHERE TRUNC(B.LOGINDTTM)>= '01-jul-2016'
  AND A.OPRID              = B.OPRID
  )
AND A.OPRID NOT IN ('OPT_BATCH','OPT_CONV','UHG_PHIRE','VP1' ,'PSIBHRFIN',
'PTWEBSERVER','LDAP_USER','GAAPBATCH','OPT_ERP_INTG')
ORDER BY 1,2;

